### ISSUE TITLE
Swar crashes/stops before new plot. Psutil acces denied

### ISSUE THREAD

**Issue by azotase** [swar/Swar-Chia-Plot-Manager#1050]
Can anyone help please. Updated swar recently and now it crashes/stops just before it's about to start a new plot. Debug log is below.

I am on Ubuntu 20.04. Swar is not in (venv)
Fresh install of Python3, pip 

If I restart it manually it will start a new plot but when that finishes it crashes again and stops.

Apologies I am a bit of a noob at linux, learning every day! :)

DEBUG.LOG

`Traceback (most recent call last):
  File "/home/plot-two/.local/lib/python3.8/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/plot-two/.local/lib/python3.8/site-packages/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/plot-two/chia-blockchain/Swar-Chia-Plot-Manager/stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "/home/plot-two/chia-blockchain/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "/home/plot-two/chia-blockchain/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 327, in start_work
    psutil.Process(pid).nice(nice_val)
  File "/home/plot-two/.local/lib/python3.8/site-packages/psutil/__init__.py", line 724, in nice
    self._proc.nice_set(value)
  File "/home/plot-two/.local/lib/python3.8/site-packages/psutil/_pslinux.py", line 1578, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=6803)`

Any help appreciated!

**Comment by racabu** [comment]
I think if I change "unix_process_priority" to something other than 0... this issue happens.

**Comment by scotianu** [comment]
> 
> 
> I think if I change "unix_process_priority" to something other than 0... this issue happens.

Yes, i comment the line with # and worked. 
Thanks @racabu

**Comment by azotase** [comment]
@racabu That worked like a treat. Thank you so much!
