### ISSUE TITLE
confirm if you have the right version. Also confirm if you have a space after the colon. "chia_location: <DRIVE>" not "chia_location:<DRIVE>"

### ISSUE THREAD

**Issue by jlfsccm** [swar/Swar-Chia-Plot-Manager#1081]
(venv) D:\Swar>python manager.py start
Traceback (most recent call last):
  File "D:\Swar\manager.py", line 30, in <module>
    start_manager()
  File "D:\Swar\plotmanager\library\utilities\commands.py", line 39, in start_manager
    test_configuration(chia_location=chia_location, notification_settings=notification_settings,
  File "D:\Swar\plotmanager\library\utilities\configuration.py", line 8, in test_configuration
    raise InvalidChiaLocationException('The chia_location in your config.yaml does not exist. Please confirm if '
plotmanager.library.utilities.exceptions.InvalidChiaLocationException: The chia_location in your config.yaml does not exist. Please confirm if you have the right version. Also confirm if you have a space after the colon. "chia_location: <DRIVE>" not "chia_location:<DRIVE>"

**Comment by jlfsccm** [comment]
chia_location: C:\Users\曹传铭\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe

**Comment by jlfsccm** [comment]
`chia_location: C:\Users\曹传铭\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe`

**Comment by jlfsccm** [comment]
> chia_location: C:\Users\曹传铭\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe
