### ISSUE TITLE
Not enough space

### ISSUE THREAD

**Issue by figaro001** [swar/Swar-Chia-Plot-Manager#1084]
Hi,

I have the command running:
    **python manager.py view**

Periodically, it crashes with the message:

Restarting view due to psutil going stale...
Traceback (most recent call last):
  File "manager.py", line 37, in <module>
    view()
  File "C:\chia\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 184, in view
    os.execv(sys.executable, system_args)
OSError: [Errno 12] Not enough space

All resources are definitely enough. This happens on three computers.

I have Python 3.8.10.

**Comment by creamsoup** [comment]
Not enough information

**Comment by Hbitvof** [comment]
I had the same today. Plenty of space left on all disks and same error.

**Comment by Dzym** [comment]
Same issue here, in different machines.

**Comment by creamsoup** [comment]
actually there is a [reddit discussion](https://www.reddit.com/r/SwarChiaPlotManager/comments/n6nbov/what_does_restarting_view_due_to_psutil_going/). it sounds like windows is not the greatest platform to run those as expected 😒
