### ISSUE TITLE
analyze_logs() - ZeroDivisionError

### ISSUE THREAD

**Issue by 350d** [swar/Swar-Chia-Plot-Manager#1097]
I have 3 plots finished (following Telegram notifications - "You completed a plot on CHIA!") with SWAR already but none of the log files contains confirmation of that. Few logs finished with error of allocation or something.
I've tried to start `analyze_logs` here:

`PS C:\Users\Chia\SWAR> python manager.py analyze_logs
Traceback (most recent call last):
  File "C:\Users\Chia\SWAR\manager.py", line 43, in <module>
    analyze_logs()
  File "C:\Users\Chia\SWAR\plotmanager\library\utilities\commands.py", line 194, in analyze_logs
    analyze_log_times(log_directory)
  File "C:\Users\Chia\SWAR\plotmanager\library\utilities\log.py", line 102, in analyze_log_times
    print(f'  phase{phase}_line_end: {int(round(sum(line_numbers[phase]) / len(line_numbers[phase]), 0))}')
ZeroDivisionError: division by zero`

Looks like some plots are not finished, others finished with errors and default config numbers for lines simply not working. I guess SWAR can do better job here to parse exact strings in log for job status confirmation, like `Copied final file from` or `Renamed final file from`

**Comment by 350d** [comment]
Well, right after I have full log in logs folder - analyze_logs was able to parse all data successfully
