### ISSUE TITLE
have a problem

### ISSUE THREAD

**Issue by jiacme** [swar/Swar-Chia-Plot-Manager#111]
Follow your tutorial, the last command, and then an error，Below is the error display

(venv) PS C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main> python manager.py start
Traceback (most recent call last):
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 102, in get_config_info
    config = _get_config()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\james\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\config.yaml", line 9, column 8

**Comment by swar** [comment]
Your YAML file is configured wrong. This is not an GitHub issue moving to discussions. 

http://www.yamllint.com/ Use this to confirm your stuff is right.
