### ISSUE TITLE
[Bug] Something wrong with dateparser in log.py

### ISSUE THREAD

**Issue by syhyz1990** [swar/Swar-Chia-Plot-Manager#112]
When the job finished , I use this command 'python manage.py view' ,it shows the error below 

```
Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "/chia/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 104, in view
    analysis = analyze_log_dates(log_directory=log_directory, analysis=analysis)
  File "/chia/Swar-Chia-Plot-Manager/plotmanager/library/utilities/log.py", line 76, in analyze_log_dates
    analysis = _get_date_summary(analysis)
  File "/chia/Swar-Chia-Plot-Manager/plotmanager/library/utilities/log.py", line 35, in _get_date_summary
    end_date = analysis['files'][file_path]['data']['date'].date()
AttributeError: 'NoneType' object has no attribute 'date'
```

**Comment by swar** [comment]
Delete the files inside of your log folder and try again.
