### ISSUE TITLE
Bug in  manager.py analyze_logs

### ISSUE THREAD

**Issue by ramonalonsocosta** [swar/Swar-Chia-Plot-Manager#1152]
When you start the service and then go to view the logs, it shows this error:

```
root@srv-chichi2:~/Swar-Chia-Plot-Manager# python3 manager.py analyze_logs
Traceback (most recent call last):
  File "manager.py", line 43, in <module>
    analyze_logs()
  File "/root/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 194, in analyze_logs
    analyze_log_times(log_directory)
  File "/root/Swar-Chia-Plot-Manager/plotmanager/library/utilities/log.py", line 102, in analyze_log_times
    print(f'phase{phase}_line_end: {int(round(sum(line_numbers[phase]) / len(line_numbers[phase]), 0))}')
ZeroDivisionError: division by zero
```

I believe that the result of the expression 'sum(total_times.values()) * 100' must be zero, since it started now. A simple test should solve the bug.

**Comment by 350d** [comment]
#1097
