### ISSUE TITLE
debug.log

### ISSUE THREAD

**Issue by selimoztur** [swar/Swar-Chia-Plot-Manager#1179]
Traceback (most recent call last):
  File "C:\Users\oztur\OneDrive\Masaüstü\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\oztur\OneDrive\Masaüstü\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.

boyle bir hata ile karşılaşıyorum ne yapmam gerek

**Comment by jack60612** [comment]
@selimoztur have you tried updating swar to the latest version?
