### ISSUE TITLE
Enhancement : :  Made a better discord update script

### ISSUE THREAD

**Issue by revantjhalani** [swar/Swar-Chia-Plot-Manager#1189]
Made a better script that handles updates on discord

Use discord.sh by https://github.com/ChaoticWeg/discord.sh.git and edit the path in the chiadiscord file accordingly

![image](https://user-images.githubusercontent.com/39228530/121610483-c760ed00-ca73-11eb-81b5-83fd849ea897.png)

[chiadiscord.zip](https://github.com/swar/Swar-Chia-Plot-Manager/files/6634921/chiadiscord.zip)

**Comment by samfisher9610** [comment]
help my concern plz 

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1256, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 34, in plots_cmd
RuntimeError: Please initialize (or migrate) your config directory with 'chia init'
[68564] Failed to execute script chia
