### ISSUE TITLE
[ERROR]: Failed to get disk_usage of drive None  What to do? 

### ISSUE THREAD

**Issue by Wraath67** [swar/Swar-Chia-Plot-Manager#1190]
Please help, I try everything I have found before, like install all new also Python, or set skip_full_destination: false, but nothing help.
The complete Error is:

2021-06-11 10:17:26 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 284, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\Users\Thors\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by Wraath67** [comment]
I find something more and it looks like the swar Plotmanager have problems with Chia 1.6 and 1.7, after I get back to 1.5 all works good.

**Comment by wacher74** [comment]
Exactly same here. 
Chia 1.1.7
Python 3.9
Windows 10 Pro
