### ISSUE TITLE
[Error]The log prompts "Length of bytes object not equal to G1Element::SIZE"

### ISSUE THREAD

**Issue by yizg20** [swar/Swar-Chia-Plot-Manager#123]
After starting the task, the log prompts the following error

[18768] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 55, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE

**Comment by yizg20** [comment]
> 启动任务后，日志提示以下错误
> 
> [18768]无法执行脚本chia
> Traceback（最近一次调用最近）：主
> 文件“ click”中的
> 文件“ chia \ cmds \ chia.py”第77行第77行，
> 单击“ chia \ cmds \ chia.py” \ core.py“，行829，在**调用**
> 文件” click \ core.py“，行782，主
> 文件” click \ core.py“，行1259，在调用
> 文件” click \ core.py“，行1259在调用
> 文件“ click \ core.py”的行1066中，在调用
> 文件“ click \ core.py”的行610中
> ，在new_func
> 文件“ chia \ cmds”中，在调用文件“ click \ decorators.py”的行21中\ plots.py”，第135行，位于create_cmd
> 文件“ chia \ plotting \ create_plots.py”，第55行，位于create_plots中
> ValueError：字节对象的长度不等于G1Element :: SIZE

I ended the python process in the task manager

**Comment by yizg20** [comment]
1

**Comment by yizg20** [comment]
> 启动任务后，日志提示以下错误
> 
> [18768]无法执行脚本chia
> Traceback（最近一次调用最近）：主
> 文件“ click”中的
> 文件“ chia \ cmds \ chia.py”第77行第77行，
> 单击“ chia \ cmds \ chia.py” \ core.py“，行829，在**调用**
> 文件” click \ core.py“，行782，主
> 文件” click \ core.py“，行1259，在调用
> 文件” click \ core.py“，行1259在调用
> 文件“ click \ core.py”的行1066中，在调用
> 文件“ click \ core.py”的行610中
> ，在new_func
> 文件“ chia \ cmds”中，在调用文件“ click \ decorators.py”的行21中\ plots.py”，第135行，位于create_cmd
> 文件“ chia \ plotting \ create_plots.py”，第55行，位于create_plots中
> ValueError：字节对象的长度不等于G1Element :: SIZE

已解决，矿池地址错误了

**Comment by WuYI-0x001** [comment]
同样错误但是确认了fpk和ppk然后没有解决

**Comment by yizg20** [comment]
> 同样错误但是确认了fpk和ppk然后没有解决

仔细检查下，不到带0x

**Comment by WuYI-0x001** [comment]
> > 同样错误但是确认了fpk和ppk然后没有解决
> 
> 仔细检查下，不到带0x

问题解决了，谢谢！
