### ISSUE TITLE
manager.py view gives an error

### ISSUE THREAD

**Issue by madislammergas** [swar/Swar-Chia-Plot-Manager#1238]
I plotting for pool. manager.py start working correctly but if I type "view" then I get an error:

Traceback (most recent call last):
  File "manager.py", line 37, in <module>
    view()
  File "C:\Users\madis\Documents\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 163, in view
    instrumentation_settings=instrumentation_settings, backend=backend)
  File "C:\Users\madis\Documents\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 290, in get_running_plots
    k_size = get_plot_k_size(commands=commands, backend=backend)
  File "C:\Users\madis\Documents\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 69, in get_plot_k_size
    return k_size_parsers.get(backend)(commands)
TypeError: _get_chia_backend_plot_k_size() missing 1 required positional argument: 'backend'

Any ideas?

**Comment by grizzlybears** [comment]
Yes, I encountered same issue.

version  d832568
chia 1.2.0
not using pool.

**Comment by terrence-c** [comment]
See my comment at https://github.com/swar/Swar-Chia-Plot-Manager/pull/1198#issuecomment-878103964

**Comment by swar** [comment]
Should be fixed
