### ISSUE TITLE
Swar plot manager Error

### ISSUE THREAD

**Issue by Yesomi** [swar/Swar-Chia-Plot-Manager#1239]
Hey i just updated to the newest version and having some problems.

yaml.scanner.ScannerError: sequence entries are not allowed here
  in "C:\Users\Chia Plotter 1\Desktop\Swar-Chia-Plot-Manager-main\config.yaml", line 13,column 10

Anyone knows whats the problem here?

Thank you in advance

Edit: fixed it but now i have a new Error if i type in Manager.py view i get this. 

C:\Users\Chia Plotter 1\Desktop\Swar-Chia-Plot-Manager-main>python manager.py view
Traceback (most recent call last):
  File "C:\Users\Chia Plotter 1\Desktop\Swar-Chia-Plot-Manager-main\manager.py", line 37, in <module>
    view()
  File "C:\Users\Chia Plotter 1\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 162, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work,
  File "C:\Users\Chia Plotter 1\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 290, in get_running_plots
    k_size = get_plot_k_size(commands=commands, backend=backend)
  File "C:\Users\Chia Plotter 1\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 69, in get_plot_k_size
    return k_size_parsers.get(backend)(commands)
TypeError: _get_chia_backend_plot_k_size() missing 1 required positional argument: 'backend'

**Comment by BinGoBinBin** [comment]
The same to me.
