### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by coins-888** [swar/Swar-Chia-Plot-Manager#1244]
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 83, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 79, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 71, in create_plots
  File "chia\util\bech32m.py", line 116, in decode_puzzle_hash
ValueError: Invalid Address
[2036] Failed to execute script chia

**Comment by yangyanhai555** [comment]
Me tooooo！

**Comment by swar** [comment]
This is a chia related error, so its most likely one of the addresses you entered in the settings is incorrect.

**Comment by coins-888** [comment]
File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 83, in
there is no file in d:\

**Comment by coins-888** [comment]
it worked thank you
