### ISSUE TITLE
bugs？please help!!

### ISSUE THREAD

**Issue by yangyanhai555** [swar/Swar-Chia-Plot-Manager#1246]
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 83, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 79, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 68, in create_plots
  File "chia\plotting\create_plots.py", line 42, in get_pool_public_key
RuntimeError: No keys, please run 'chia keys add', 'chia keys generate' or provide a public key with -p
[9204] Failed to execute script chia
![error](https://user-images.githubusercontent.com/76138281/125475795-99dd7113-7bcf-461f-9ca2-0b91ffb5e6b6.png)

**Comment by ShadXo** [comment]
What are you trying to do? The current version doesn't support pooling as far I know.
Use the files from: https://github.com/jack60612/Swar-Chia-Plot-Manager

**Comment by swar** [comment]
> What are you trying to do? The current version doesn't support pooling as far I know.
> Use the files from: https://github.com/jack60612/Swar-Chia-Plot-Manager

It does support pooling, changes were made around 1-2 weeks ago.

**Comment by ShadXo** [comment]
Ah nice, it didn't when I checked and saw no new version.

**Comment by LotharMadsson** [comment]
@ShadXo There was no new release tag. Simply clone the repo and you are fine.

**Comment by ShadXo** [comment]
@LotharMadsson No worries, I got it already working around 2 weeks ago.
