### ISSUE TITLE
_get_chia_flags() got an unexpected keyword argument 'threadX_p2'

### ISSUE THREAD

**Issue by bilalwaheedch** [swar/Swar-Chia-Plot-Manager#1254]
Getting the following error (debug.log) with latest commit:

Traceback (most recent call last):
  File "/home/bilal/Swar-Chia-Plot-Manager/stateless-manager.py", line 109, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "/home/bilal/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 276, in monitor_jobs_to_start
    job, work = start_work(
  File "/home/bilal/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 325, in start_work
    plot_command = plots.create(
  File "/home/bilal/Swar-Chia-Plot-Manager/plotmanager/library/commands/plots.py", line 6, in create
    backend_flags = _get_backend_flags(backend, *args, **kwargs)
  File "/home/bilal/Swar-Chia-Plot-Manager/plotmanager/library/commands/plots.py", line 38, in _get_backend_flags
    return backend_parser(*args, **kwargs)
TypeError: _get_chia_flags() got an unexpected keyword argument 'threadX_p2'

**Comment by swar** [comment]
@bilalwaheedch  got ahead of myself with the merge. I pushed out a fix, let me know if that works for you now.

**Comment by bilalwaheedch** [comment]
Successfully able to start the manager now. Thanks!
