### ISSUE TITLE
Cannot start Swar

### ISSUE THREAD

**Issue by ADT03** [swar/Swar-Chia-Plot-Manager#1257]
Hi,

I cann't start Swar, the error log is:

(venv) PS I:\Swar-Chia-Plot-Manager-main> python manager.py start
Traceback (most recent call last):
  File "I:\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "I:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.

And debug.log:

Traceback (most recent call last):
  File "I:\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 109, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "I:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 212, in monitor_jobs_to_start
    drives_free_space = get_drives_free_space(jobs, system_drives, running_work)
  File "I:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 189, in get_drives_free_space
    if drive[-1] == '/' or drive[-1] == '\\':
TypeError: 'NoneType' object is not subscriptable

Please help to advice, thanks alot.

**Comment by ADT03** [comment]
Debug log is:

2021-07-19 07:16:24 [INFO]: Starting loop.
2021-07-19 07:16:24 [INFO]: Checking log progress..
2021-07-19 07:16:24 [INFO]: Checking log progress for PID: 12292
2021-07-19 07:16:24 [INFO]: PID still alive: 12292
2021-07-19 07:16:24 [INFO]: Checking log progress for PID: 11212
2021-07-19 07:16:24 [INFO]: PID still alive: 11212
2021-07-19 07:16:24 [INFO]: Clearing zombies
2021-07-19 07:16:24 [INFO]: Monitoring jobs to start.
2021-07-19 07:16:24 [INFO]: Free space before checking active jobs: {'G:': 531749019648}
Traceback (most recent call last):
  File "I:\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 109, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "I:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 212, in monitor_jobs_to_start
    drives_free_space = get_drives_free_space(jobs, system_drives, running_work)
  File "I:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 189, in get_drives_free_space
    if drive[-1] == '/' or drive[-1] == '\\':
TypeError: 'NoneType' object is not subscriptable

**Comment by ADT03** [comment]
Hi, 

Restart the system, and can run swar now. Thanks all,
