### ISSUE TITLE
[8492] Failed to execute script chia

### ISSUE THREAD

**Issue by quan-tanamo** [swar/Swar-Chia-Plot-Manager#1284]
Hi hi,

My log is spitting out a failure to execute script chia. I'm fairly new to this. I am coming over from using the Chia GUI. This is the following log:

Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 83, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 79, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 64, in create_plots
ValueError: non-hexadecimal number found in fromhex() arg at position 0
[8492] Failed to execute script chia

**Comment by quan-tanamo** [comment]
it was the keys hexadecimal issue that was addressed in other tags. I misunderstood the pool_public_key for the pool contract address. Closing issue.
