### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by AdianRND** [swar/Swar-Chia-Plot-Manager#129]
Error when start manager.py
Powershell run as administrator
Temp dir ACL full permission to ALL

2021-05-06 21:44:47 [INFO]: Debug Level: INFO
2021-05-06 21:44:47 [INFO]: Chia Location: C:\Users\Admin\AppData\Local\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon\chia
2021-05-06 21:44:47 [INFO]: Log Directory: C:\Swar-main\logs
2021-05-06 21:44:47 [INFO]: Jobs: [{'name': 'RAM', 'max_plots': 999, 'farmer_public_key': None, 'pool_public_key': None, 'temporary_directory': 'R:\\TMP', 'temporary2_directory': None, 'destination_directory': 'D:\\XCH2', 'size': 32, 'bitfield': True, 'threads': 8, 'buckets': 128, 'memory_buffer': 10000, 'max_concurrent': 2, 'max_concurrent_with_start_early': 7, 'stagger_minutes': 60, 'max_for_phase_1': 1, 'concurrency_start_early_phase': 4, 'concurrency_start_early_phase_delay': 0, 'temporary2_destination_sync': False}, {'name': 'Drive_C', 'max_plots': 999, 'farmer_public_key': None, 'pool_public_key': None, 'temporary_directory': 'C:\\TMP', 'temporary2_directory': None, 'destination_directory': 'D:\\XCH2', 'size': 32, 'bitfield': True, 'threads': 8, 'buckets': 128, 'memory_buffer': 5000, 'max_concurrent': 1, 'max_concurrent_with_start_early': 3, 'stagger_minutes': 180, 'max_for_phase_1': 1, 'concurrency_start_early_phase': 4, 'concurrency_start_early_phase_delay': 0, 'temporary2_destination_sync': False}, {'name': 'Drive_D', 'max_plots': 999, 'farmer_public_key': None, 'pool_public_key': None, 'temporary_directory': 'D:\\TMP', 'temporary2_directory': None, 'destination_directory': 'D:\\XCH2', 'size': 32, 'bitfield': True, 'threads': 8, 'buckets': 128, 'memory_buffer': 5000, 'max_concurrent': 1, 'max_concurrent_with_start_early': 3, 'stagger_minutes': 180, 'max_for_phase_1': 1, 'concurrency_start_early_phase': 4, 'concurrency_start_early_phase_delay': 0, 'temporary2_destination_sync': False}]
2021-05-06 21:44:47 [INFO]: Manager Check Interval: 30
2021-05-06 21:44:47 [INFO]: Max Concurrent: 5
2021-05-06 21:44:47 [INFO]: Progress Settings: {'phase1_line_end': 801, 'phase2_line_end': 834, 'phase3_line_end': 2474, 'phase4_line_end': 2620, 'phase1_weight': 33.4, 'phase2_weight': 20.43, 'phase3_weight': 42.29, 'phase4_weight': 3.88}
2021-05-06 21:44:47 [INFO]: Notification Settings: {'notify_discord': False, 'discord_webhook_url': 'https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'notify_sound': False, 'song': 'audio.mp3', 'notify_pushover': False, 'pushover_user_key': 'xx', 'pushover_api_key': 'xx', 'notify_twilio': False, 'twilio_account_sid': 'xxxxx', 'twilio_auth_token': 'xxxxx', 'twilio_from_phone': 1234657890, 'twilio_to_phone': 1234657890}
2021-05-06 21:44:47 [INFO]: View Settings: {'check_interval': 30, 'datetime_format': '%Y-%m-%d %H:%M:%S', 'include_seconds_for_phase': False, 'include_drive_info': True, 'include_cpu': True, 'include_ram': True, 'include_plot_stats': True}
2021-05-06 21:44:47 [INFO]: Loading jobs into objects.
2021-05-06 21:44:47 [INFO]: Grabbing running plots.
2021-05-06 21:44:47 [INFO]: Getting running plots
2021-05-06 21:44:47 [INFO]: Finished finding running plots
2021-05-06 21:44:47 [INFO]: Starting loop.
2021-05-06 21:44:47 [INFO]: Checking log progress..
2021-05-06 21:44:47 [INFO]: Monitoring jobs to start.
2021-05-06 21:44:47 [INFO]: Checking to queue work for job: RAM
2021-05-06 21:44:47 [INFO]: Total jobs in phase 1: 0
2021-05-06 21:44:47 [INFO]: Calculating new job stagger time. Next stagger kickoff: 2021-05-06 22:44:47.226706
2021-05-06 21:44:47 [INFO]: Starting new plot for job: RAM
2021-05-06 21:44:47 [INFO]: Job log file path: C:\Swar-main\logs\RAM_2021-05-06_21_44_47_226706.log
2021-05-06 21:44:47 [INFO]: Job destination directory: D:\XCH2
2021-05-06 21:44:47 [INFO]: Job temporary2 directory: None
2021-05-06 21:44:47 [INFO]: Starting with plot command: ['C:\\Users\\Admin\\AppData\\Local\\chia-blockchain\\app-1.1.4\\resources\\app.asar.unpacked\\daemon\\chia', 'plots', 'create', '-k', '32', '-b', '10000', '-t', 'R:\\TMP', '-d', 'D:\\XCH2', '-r', '8', '-u', '128']
2021-05-06 21:44:47 [INFO]: Starting process
Traceback (most recent call last):
  File "C:\Swar\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Swar\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Swar\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Swar\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Отказано в доступе

**Comment by PastaRhymes** [comment]
Did you add the file name in the chia location as well (chia.exe). Path alone is not enough.

**Comment by AdianRND** [comment]
Thx, it works
