### ISSUE TITLE
manager start with error

### ISSUE THREAD

**Issue by nvkosykh** [swar/Swar-Chia-Plot-Manager#138]
[4204] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 55, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE

config
chia_location: C:\Users\miner\AppData\Local\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon\chia.exe
manager:
  check_interval: 60
  log_level: INFO

log:
  folder_path: C:\Plot_mgr\Logs\Plotter

view:
  check_interval: 60
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: true
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true

notifications:
  notify_discord: false
  discord_webhook_url: https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  notify_sound: false
  song: audio.mp3
  notify_pushover: false
  pushover_user_key: xx
  pushover_api_key: xx
  notify_twilio: false
  twilio_account_sid: xxxxx
  twilio_auth_token: xxxxx
  twilio_from_phone: +1234657890
  twilio_to_phone: +1234657890
progress:
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88

global:
  max_concurrent: 10

jobs:
  - name: garage
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: D:\
    temporary2_directory:
    destination_directory:
      - F:\
      - H:\
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 4500
    max_concurrent: 15
    max_concurrent_with_start_early: 7
    stagger_minutes: 10
    max_for_phase_1: 2
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

**Comment by nvkosykh** [comment]
problem with ppk and fpk
in command to start plot they put in integer
