### ISSUE TITLE
Start Manager on Mac OS

### ISSUE THREAD

**Issue by carfnann** [swar/Swar-Chia-Plot-Manager#143]
Hi

I wanted to run Plot Manager on my Mac, but I'm not able to...
here the message after the launch
```
(venv) toto@Mac-mini Swar-Chia-Plot-Manager % sudo python3 manager.py start
Password:
Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "/Users/toto/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.
(venv) totgo@Mac-mini Swar-Chia-Plot-Manager % python3 manager.py start     
Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "/Users/toto/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.
```

Here the log file : 

```
Traceback (most recent call last):
  File "/Users/toto/Swar-Chia-Plot-Manager/stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "/Users/toto/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "/Users/toto/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "/Users/toto/Swar-Chia-Plot-Manager/plotmanager/library/utilities/processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon'
```

What should I do?
thanks

**Comment by rigirigi** [comment]
I had the same issue on my Mac.  You need the chia location to point to the application, not just the directory.

In the config.yaml file, it should work if you replace /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon with /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/chia

Also you don't need to run under sudo.
