### ISSUE TITLE
Progress is not being accurately reflected in viewer

### ISSUE THREAD

**Issue by ausyau** [swar/Swar-Chia-Plot-Manager#149]
For some reason, progress is getting stuck, Notice how I'm on Phase 4, yet it says progress is in the 60's. 

![image](https://user-images.githubusercontent.com/43872763/117508924-31024e80-af3e-11eb-9706-290c7c05ff6f.png)

Eventually, an error like this occurs
```
Traceback (most recent call last):
  File "C:\Users\Leviathan\Chia\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Leviathan\Chia\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\_pswindows.py", line 993, in open_files
    raw_file_names = cext.proc_open_files(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Leviathan\Chia\Swar-Chia-Plot-Manager\manager.py", line 36, in <module>
    view()
  File "C:\Users\Leviathan\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "C:\Users\Leviathan\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 200, in get_running_plots
    for file in process.open_files():
  File "C:\Users\Leviathan\Chia\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\__init__.py", line 1138, in open_files
    return self._proc.open_files()
  File "C:\Users\Leviathan\Chia\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=39828, name='chia.exe')
```

**Comment by andrewmantovani** [comment]
Nothing to do with your issue but looking at the screenshot you would be better off shifting some of your temp drives to other systems. You are running into a bottleneck and im not sure which it is. Maybe not enough bandwith for nvme drives? I have some of the same drives in a xeon v3 which is 7+ year old now outperforming your times. 

I notice the same type of bottleneck where it can't be drives and CPU utilization is under 50% with plenty of ram left. Could be we are maxing out pcie lanes on older systems??

**Comment by ausyau** [comment]
@andrewmantovani 
Yeah, this is a threadripper system so I think we're still maxing out bandwith for the nvme drives which is kind of annoying. I haven't been able to figure out other ways to optimize this and I'm not super keen on investing in another machine to plot just yet. =\

**Comment by swar** [comment]
@ausyau There's a small easter egg where you can run `python manager.py analyze_logs` and it will analyze all completed log files in the log folder you referenced in config.yaml and then it will spit out values for your own system. Give that a shot :)
