### ISSUE TITLE
Start Error - PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by Taipan24** [swar/Swar-Chia-Plot-Manager#154]
I have an error when starting the manager. Also tried running cmd window with Administrator privileges and still got an error.
Win10, Python 3.9.5. Following is an INFO level log.

2021-05-08 03:35:11 [INFO]: Debug Level: INFO
2021-05-08 03:35:11 [INFO]: Chia Location: C:\Users\User\AppData\Local\Chia-Blockchain\app-1.1.4\resources\app.asar.unpacked\daemon
2021-05-08 03:35:11 [INFO]: Log Directory: c:\Temp\Chia.Logs
2021-05-08 03:35:11 [INFO]: Jobs: [{'name': 'Plotter', 'max_plots': 999, 'farmer_public_key': None, 'pool_public_key': None, 'temporary_directory': 'C:\\Temp\\Chia.Temp', 'temporary2_directory': None, 'destination_directory': 'C:\\Temp\\Chia.Plots', 'size': 32, 'bitfield': True, 'threads': 8, 'buckets': 128, 'memory_buffer': 5000, 'max_concurrent': 6, 'max_concurrent_with_start_early': 7, 'stagger_minutes': 110, 'max_for_phase_1': 3, 'concurrency_start_early_phase': 4, 'concurrency_start_early_phase_delay': 0, 'temporary2_destination_sync': False}]
2021-05-08 03:35:11 [INFO]: Manager Check Interval: 60
2021-05-08 03:35:11 [INFO]: Max Concurrent: 6
2021-05-08 03:35:11 [INFO]: Progress Settings: {'phase1_line_end': 801, 'phase2_line_end': 834, 'phase3_line_end': 2474, 'phase4_line_end': 2620, 'phase1_weight': 33.4, 'phase2_weight': 20.43, 'phase3_weight': 42.29, 'phase4_weight': 3.88}
2021-05-08 03:35:11 [INFO]: Notification Settings: {'notify_discord': False, 'discord_webhook_url': 'https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'notify_sound': False, 'song': 'audio.mp3', 'notify_pushover': False, 'pushover_user_key': 'xx', 'pushover_api_key': 'xx', 'notify_twilio': False, 'twilio_account_sid': 'xxxxx', 'twilio_auth_token': 'xxxxx', 'twilio_from_phone': 1234657890, 'twilio_to_phone': 1234657890}
2021-05-08 03:35:11 [INFO]: View Settings: {'check_interval': 60, 'datetime_format': '%Y-%m-%d %H:%M:%S', 'include_seconds_for_phase': False, 'include_drive_info': True, 'include_cpu': True, 'include_ram': True, 'include_plot_stats': True}
2021-05-08 03:35:11 [INFO]: Loading jobs into objects.
2021-05-08 03:35:11 [INFO]: Grabbing running plots.
2021-05-08 03:35:11 [INFO]: Getting running plots
2021-05-08 03:35:11 [INFO]: Found chia plotting process: 3864
2021-05-08 03:35:11 [INFO]: Found chia plotting process: 5280
2021-05-08 03:35:11 [INFO]: Found chia plotting process: 13980
2021-05-08 03:35:11 [INFO]: Found chia plotting process: 14088
2021-05-08 03:35:11 [INFO]: Finding log file for process: 13980
2021-05-08 03:35:11 [INFO]: Found log file: C:\Temp\Chia.Logs\log.20210507.2016.log
2021-05-08 03:35:11 [INFO]: Finding associated job
2021-05-08 03:35:11 [INFO]: Finding log file for process: 5280
2021-05-08 03:35:11 [INFO]: Found log file: C:\Temp\Chia.Logs\log.20210507.2213.log
2021-05-08 03:35:11 [INFO]: Finding associated job
2021-05-08 03:35:11 [INFO]: Finding log file for process: 14088
2021-05-08 03:35:11 [INFO]: Found log file: C:\Temp\Chia.Logs\log.20210507.2222.log
2021-05-08 03:35:11 [INFO]: Finding associated job
2021-05-08 03:35:11 [INFO]: Finding log file for process: 3864
2021-05-08 03:35:11 [INFO]: Found log file: C:\Temp\Chia.Logs\log.20210507.2309.log
2021-05-08 03:35:11 [INFO]: Finding associated job
2021-05-08 03:35:11 [INFO]: Finished finding running plots
2021-05-08 03:35:11 [INFO]: Starting loop.
2021-05-08 03:35:11 [INFO]: Checking log progress..
2021-05-08 03:35:11 [INFO]: Checking log progress for PID: 13980
2021-05-08 03:35:11 [INFO]: PID still alive: 13980
2021-05-08 03:35:11 [INFO]: Checking log progress for PID: 5280
2021-05-08 03:35:11 [INFO]: PID still alive: 5280
2021-05-08 03:35:11 [INFO]: Checking log progress for PID: 14088
2021-05-08 03:35:11 [INFO]: PID still alive: 14088
2021-05-08 03:35:11 [INFO]: Checking log progress for PID: 3864
2021-05-08 03:35:11 [INFO]: PID still alive: 3864
2021-05-08 03:35:11 [INFO]: Monitoring jobs to start.
2021-05-08 03:35:11 [INFO]: Checking to queue work for job: Plotter
2021-05-08 03:35:11 [INFO]: Total jobs in phase 1: 0
2021-05-08 03:35:11 [INFO]: Calculating new job stagger time. Next stagger kickoff: 2021-05-08 05:25:11.970197
2021-05-08 03:35:11 [INFO]: Starting new plot for job: Plotter
2021-05-08 03:35:11 [INFO]: Job log file path: c:\Temp\Chia.Logs\Plotter_2021-05-08_03_35_11_970197.log
2021-05-08 03:35:11 [INFO]: Job destination directory: C:\Temp\Chia.Plots
2021-05-08 03:35:11 [INFO]: Job temporary2 directory: None
2021-05-08 03:35:11 [INFO]: Starting with plot command: ['C:\\Users\\User\\AppData\\Local\\Chia-Blockchain\\app-1.1.4\\resources\\app.asar.unpacked\\daemon', 'plots', 'create', '-k', '32', '-b', '5000', '-t', 'C:\\Temp\\Chia.Temp', '-d', 'C:\\Temp\\Chia.Plots', '-r', '8', '-u', '128']
2021-05-08 03:35:11 [INFO]: Starting process
Traceback (most recent call last):
  File "C:\Temp\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Temp\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Temp\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Temp\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by DarthyX** [comment]
I had the same problem and solved it by correcting my chia_location path in the config.yaml
I had the path ending with ..../daemon/chia instead of the **correct** ..../daemon/**chia.exe**

**Comment by Taipan24** [comment]
That was it - Solved. Thanks a lot!

**Comment by DarthyX** [comment]
Glad to have helped!!  It took me hours of investigating paths and security rights to end up to this simple solution.  The error description "Access is denied" is misleading to say the least...
