### ISSUE TITLE
stderr: [1392] Failed to execute script start_farmer

### ISSUE THREAD

**Issue by zhangze1243** [swar/Swar-Chia-Plot-Manager#162]
Ask for help, log error after running the program：
stderr: [1392] Failed to execute script start_farmer

Traceback (most recent call last):

  File "chia\server\start_farmer.py", line 68, in <module>

  File "chia\server\start_farmer.py", line 64, in main

  File "chia\server\start_service.py", line 218, in run_service

  File "asyncio\runners.py", line 43, in run

  File "asyncio\base_events.py", line 587, in run_until_complete

  File "chia\server\start_service.py", line 212, in async_run_service

  File "chia\server\start_service.py", line 156, in run

  File "chia\server\start_service.py", line 132, in start

  File "chia\server\server.py", line 213, in start_server

  File "aiohttp\web_runner.py", line 128, in start

  File "asyncio\base_events.py", line 1389, in create_server

OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8447): ͨ��ÿ���׽��ֵ�ַ(Э��/�����ַ/�˿�)ֻ����ʹ��һ�Ρ�

**Comment by swar** [comment]
Please use GitHub Discussions for questions as this is not an Issue.

This is related to Chia anyways, contact them.
