### ISSUE TITLE
[2444] Failed to execute script chia

### ISSUE THREAD

**Issue by WuYI-0x001** [swar/Swar-Chia-Plot-Manager#176]
[2444] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 55, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE

Is there anyone konw what's wrong?

**Comment by Uinden** [comment]
Delete ppk and fpk from config  
https://github.com/swar/Swar-Chia-Plot-Manager/issues/136#issuecomment-834078314

**Comment by WuYI-0x001** [comment]
delete the "0x" in fpk and ppk
