### ISSUE TITLE
python 

### ISSUE THREAD

**Issue by aladingDenson** [swar/Swar-Chia-Plot-Manager#179]
Hello, I want to know why the program is packaged into manager.exe, run start_manager, and then call the subprocess.Popen method, but the chai.exe process is not created. On my computer, run manager.py directly for GUI operation. No problem.

**Comment by aladingDenson** [comment]
```
C:\Users\abc\AppData\Local\chia-blockchain\app-1.0.5\resources\app.asar.unpacked\daemon\chia.exe
['C:\\Users\\abc\\Desktop\\yuan-chia-plot-manager\\venv\\Scripts\\pythonw.exe', 'C:\\Users\\abc\\Desktop\\yuan-chia-plot-manager\\stateless-manager.py']
<subprocess.Popen object at 0x0000018E55BC4388>
[psutil.Process(pid=6452, name='pythonw.exe', status='running', started='20:46:41'), psutil.Process(pid=8084, name='pythonw.exe', status='running', started='20:46:41')]
Plot Manager has started...
[psutil.Process(pid=6452, name='pythonw.exe', status='running', started='20:46:41'), psutil.Process(pid=8084, name='pythonw.exe', status='running', started='20:46:41')]
[]
Successfully stopped manager processes.
```
this is my computer running, all is right

```
C:\Users\abc\AppData\Local\chia-blockchain\app-1.0.5\resources\app.asar.unpacked\daemon\chia.exe
['C:\\Users\\abc\\Desktop\\yuan-chia-plot-manager\\dist\\manager.exe', 'C:\\Users\\abc\\Desktop\\yuan-chia-plot-manager\\dist\\stateless-manager.py']
<subprocess.Popen object at 0x000002ABF15DC888>
[]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "manager.py", line 53, in start
  File "plotmanager\library\utilities\commands.py", line 60, in start_manager
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.
```  
This is the display controlled after being packaged into manager.exe and running。

**Comment by aladingDenson** [comment]
Just now, I used pyinstaller to package another small program, which also contains subprocess.popen. Fortunately, the packaged test.exe program runs normally. I think there is a problem with stateless-manager.py, you can try it

**Comment by swar** [comment]
There is no problem with stateless-manager.py, you are just doing things that this library was not meant to do or designed for. Specifically packaging them into executables. This seems like something you need to resolve on your own end.
