### ISSUE TITLE
Urgent after 1.1.4 nothing works!

### ISSUE THREAD

**Issue by gntz555** [swar/Swar-Chia-Plot-Manager#180]
2021-05-09 17:46:33 [INFO]: Manager Check Interval: 60
2021-05-09 17:46:33 [INFO]: Max Concurrent: 12
2021-05-09 17:46:33 [INFO]: Progress Settings: {'phase1_line_end': 801, 'phase2_line_end': 834, 'phase3_line_end': 2474, 'phase4_line_end': 2620, 'phase1_weight': 33.4, 'phase2_weight': 20.43, 'phase3_weight': 42.29, 'phase4_weight': 3.88}
2021-05-09 17:46:33 [INFO]: Notification Settings: {'notify_discord': True, 'discord_webhook_url': 'edit', 'notify_sound': False, 'song': 'audio.mp3', 'notify_pushover': False, 'pushover_user_key': 'xx', 'pushover_api_key': 'xx', 'notify_twilio': False, 'twilio_account_sid': 'xxxxx', 'twilio_auth_token': 'xxxxx', 'twilio_from_phone': 1234657890, 'twilio_to_phone': 1234657890}
2021-05-09 17:46:33 [INFO]: View Settings: {'check_interval': 30, 'datetime_format': '%Y-%m-%d %H:%M:%S', 'include_seconds_for_phase': False, 'include_drive_info': True, 'include_cpu': True, 'include_ram': True, 'include_plot_stats': True}
2021-05-09 17:46:33 [INFO]: Loading jobs into objects.
2021-05-09 17:46:33 [INFO]: Grabbing running plots.
2021-05-09 17:46:33 [INFO]: Getting running plots
2021-05-09 17:46:33 [INFO]: Finished finding running plots
2021-05-09 17:46:33 [INFO]: Starting loop.
2021-05-09 17:46:33 [INFO]: Checking log progress..
2021-05-09 17:46:33 [INFO]: Monitoring jobs to start.
2021-05-09 17:46:33 [INFO]: Checking to queue work for job: micron
2021-05-09 17:46:33 [INFO]: Total jobs in phase 1: 0
2021-05-09 17:46:33 [INFO]: Calculating new job stagger time. Next stagger kickoff: 2021-05-09 18:01:33.751176
2021-05-09 17:46:33 [INFO]: Starting new plot for job: micron
2021-05-09 17:46:33 [INFO]: Job log file path: C:\Chia\Logs\Plotter\micron_2021-05-09_17_46_33_751176.log
2021-05-09 17:46:33 [INFO]: Job destination directory: D:\chia_final_plot_directory
2021-05-09 17:46:33 [INFO]: Job temporary2 directory: D:\chia_HDD_tmp
2021-05-09 17:46:33 [INFO]: Starting with plot command: ['C:\\Users\\msgAZ\\AppData\\Local\\chia-blockchain\\app-1.1.3\\resources\\app.asar.unpacked\\daemon\\chia.exe', 'plots', 'create', '-k', '32', '-b', '2800', '-t', 'E:\\plot_tmp', '-d', 'D:\\chia_final_plot_directory', '-r', '32', '-u', '128', '-2', 'D:\\chia_HDD_tmp']
2021-05-09 17:46:33 [INFO]: Starting process
Traceback (most recent call last):
  File "C:\Swar-Chia-Plot-Manager\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 273, in start_process
    process = subprocess.Popen(
  File "C:\Users\msgAZ\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\msgAZ\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by gntz555** [comment]
I downgraded to 1.1.3 and the manager does run. However all plotting progress is lost.

**Comment by aladingDenson** [comment]
this is very like subprocess.py Incompatibility，Similar to the last issue I asked

**Comment by Uinden** [comment]
Are you sure `C:\Users\msgAZ\AppData\Local\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon\chia.exe` exists?

**Comment by swar** [comment]
This indicates to me that your chia_location is wrong. As @Uinden  suggested please check if that's the case or not.

**Comment by 0x13ens** [comment]
you need C:\Users\msgAZ\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe after update.

**Comment by gumush** [comment]
not working after updating path of chia.exe

**Comment by gumush** [comment]
> you need
> 
> `C:\Users\msgAZ\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe `
> 
> after update.

not working after updating path of chia.exe

**Comment by swar** [comment]
> > you need
> > `C:\Users\msgAZ\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe `
> > after update.
> 
> not working after updating path of chia.exe

Did you update the username to your own username?

**Comment by gntz555** [comment]
> Are you sure `C:\Users\msgAZ\AppData\Local\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon\chia.exe` exists?

Thank you very much! Also @swar thank you very much!! I didn't had time to report back because I used the unexpected "downtime" of my PC for some changes.
