### ISSUE TITLE
Unable to start manager after 1.1.5 update to Chia

### ISSUE THREAD

**Issue by Fate0025** [swar/Swar-Chia-Plot-Manager#187]
Hi I was able to run the plot manager fine just yesterday in Chia version 1.1.4.
But I just updated to Chia version 1.1.5.

I made sure to update my cli location in config.yaml
[config.yaml.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6448574/config.yaml.txt)

chia_location: C:\Users\Charlie\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon

When I tried starting the manager I got this error in commandprompt
Traceback (most recent call last):
  File "C:\Users\Charlie\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\Charlie\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.

And when I went into the manager.log to check these were the errors:
Traceback (most recent call last):
  File "C:\Users\Charlie\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\Charlie\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Users\Charlie\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Users\Charlie\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by swar** [comment]
You didn't update chia_location

**Comment by Fate0025** [comment]
Oh I see, I needed to include the whole path name to the exe, not just the folder. Found the answer among the discussions.
C:\Users\Charlie\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe
