### ISSUE TITLE
error with 3 plots in parallel or more, but continue slow

### ISSUE THREAD

**Issue by joselcl98** [swar/Swar-Chia-Plot-Manager#205]
Traceback (most recent call last):
  File "C:\Users\LCL\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\LCL\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 993, in open_files
    raw_file_names = cext.proc_open_files(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LCL\Documents\Swar-Chia-Plot-Manager-main\manager.py", line 36, in <module>
    view()
  File "C:\Users\LCL\Documents\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "C:\Users\LCL\Documents\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 203, in get_running_plots
    for file in process.open_files():
  File "C:\Users\LCL\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\__init__.py", line 1138, in open_files
    return self._proc.open_files()
  File "C:\Users\LCL\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=18212, name='chia.exe')
PS C:\Users\LCL\Documents\Swar-Chia-Plot-Manager-main>

[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6452222/config.txt)

**Comment by swar** [comment]
Try version 0.1.0 to see if it fixes your issues.
https://github.com/swar/Swar-Chia-Plot-Manager/releases/tag/v.0.1.0
