### ISSUE TITLE
stopped starting with Chia Blockchain 1.1.5

### ISSUE THREAD

**Issue by nort774** [swar/Swar-Chia-Plot-Manager#208]
Reinstalled several times, stopped working with 1.1.5

(venv) PS C:\Users\Chia\Swar-Chia-Plot-Manager-main> python manager.py start
Traceback (most recent call last):
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 102, in get_config_info
    config = _get_config()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\Chia\Swar-Chia-Plot-Manager-main\config.yaml", line 138, column 27

**Comment by swar** [comment]
Your YAML syntax is wrong. Check indenting. 
http://www.yamllint.com/

**Comment by nort774** [comment]
thanks a ton this solved the problem, but there are still some problems
PermissionError: [WinError 5]
i try to solve them
