### ISSUE TITLE
FileNotFoundError: [WinError 3

### ISSUE THREAD

**Issue by bibiboui** [swar/Swar-Chia-Plot-Manager#249]
(venv) C:\Users\NB\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\NB\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\NB\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "C:\Users\NB\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 107, in get_config_info
    os.makedirs(log_directory)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\NB\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'S:\\'

can someone help me?

**Comment by VeeTeeF** [comment]
I'm getting the exact same type of error since restarting the manager last night.

**Comment by spacewaffles309** [comment]
In config.yaml, you need to set the folder_path on line 21 to be your actual drive/directory for logs.  In the default, it is S:\Chia\Logs\Plotter , but if you don't have an S: drive and those folders, well... there's your problem.

**Comment by bibiboui** [comment]
thx but now i have this probleme
(venv) C:\Users\NB\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\NB\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\NB\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.

**Comment by spacewaffles309** [comment]
What's manager.log say?

**Comment by swar** [comment]
Please use GitHub Discussions for questions as this is not an Issue.
