### ISSUE TITLE
destination_directory:  over network?

### ISSUE THREAD

**Issue by Neosettler** [swar/Swar-Chia-Plot-Manager#260]
Greetings,

Could anyone confirm that copying over the network to a shared folder is possible?

Edit: Using windows 10

destination_directory:  \\myComputer\chiaSharedFolder

So far the file is not being copied but I'm not sure if there is some other factor involved.

Thank you,

**Comment by spacewaffles309** [comment]
I think the destination would need to be \\myComputer instead of just a single \, or add it as a mapped network drive and use the new assigned drive letter.  Depending on your network speed, this can increase the time to finish a plot by quite a bit, because it considers the final move/transfer time as part of plotting.  If you have another local place to move it to first, that might help keep things moving along faster.

**Comment by kilrah** [comment]
If my destination directory is over the network on Windows (whether path is specified with the \\ or as a mapped drive with drive letter) in both cases the manager won't start with the following error:

```2021-05-13 10:33:33 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 155, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\stateless-manager.py", line 73, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 219, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 244, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 24, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 51, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\Users\me\Documents\Repos\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Comment by DaT1ck** [comment]
I use it over Windows network and have the following set in the config file:

destination_directory: \\DESKTOP-XXXXX\Chia5

The only other thing I've needed to do was change the sharing permissions to allow for WRITE access.  I'm assuming you're set to WRITE and there's free space?

**Comment by wirespeed43** [comment]
Try mapping the remote directory as a drive.

**Comment by tritechnik** [comment]
I've tried both ways and neither lets me start manager.py

**Comment by wirespeed43** [comment]
Can you upload your config?

**Comment by tritechnik** [comment]
I've already edited mine, and just wrote a batch script to move it off the nvme to the network share, but I tried "Z:\" (tried upper and lower case), as well as \\SERVER\Share.

**Comment by swar** [comment]
Is this resolved? Network drives with letters do not work, you need to use the network file path as @DaT1ck  suggested.

**Comment by Neosettler** [comment]
Yes, destination folder over network successful with \\192.168.X.X\myFolder format. Thank you!

**Comment by bw-man** [comment]
this is not working:   \192.168.X.X\myFolder 
it will create a folder on C:\192.168.x.x\

**Comment by bw-man** [comment]
@swar why you close it ? It is not solved

**Comment by kilrah** [comment]
Could it be that 

`destination_directory: \\machine\share` 

deosn't work but 
```
destination_directory: 
  - \\machine\share
```

does, or vice versa and it just needs clarifying in the doc? I only checked one but don't remember which, probably the former.

**Comment by bw-man** [comment]
i have Windows 10.

This:
destination_directory: 
  - \\machine\share

is not working. He dont like the -
And i do that with Powershell as Administrator.
