### ISSUE TITLE
PermissionError: [WinError 5] Acces Denied

### ISSUE THREAD

**Issue by cygair** [swar/Swar-Chia-Plot-Manager#267]
Hi all, 

I installed python 3.9 with success on W10.

`pip install -r requirements.txt` runs smoothly.

Copied and modified the config.yaml with thee following below joined.
[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6467605/config.txt)

When I run `python manager.py start` I get the following error : 
`Traceback (most recent call last):
  File "C:\developpements\Swar-Chia-Plot-Manager\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\developpements\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\developpements\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\developpements\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Users\cgair\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\cgair\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Accès refusé`

I tried with admin right, but without success.

Thanks.

**Comment by Taipan24** [comment]
chia_location parameter should end with "\daemon\chia.exe"

**Comment by cygair** [comment]
> chia_location parameter should end with "\daemon\chia.exe"

Yes thanks !
