### ISSUE TITLE
Permission  Error with MacOS (PermissionError: [Errno 13] Permission denied)

### ISSUE THREAD

**Issue by Jjjameson91** [swar/Swar-Chia-Plot-Manager#269]
I can't seem to get the plot manager to play nice with my MacOS Chia app. I believe I have the correct path to the application (Please correct me if I'm wrong!), but no matter what I do, I get a permission denied error. 

Note: If I use a slightly different path to the app, I can get it to load without error and see the running jobs, but it can't interact (add new plots).

These are the variable values I have tried for the app path:

chia_location: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon

OR

chia_location: /Applications/Chia.app/Contents/MacOS/Chia
(Loads without error, but does not 'connect')

I have followed the steps outlined, including the optional venv virtual environment step. I have updated python to 3.9.4. I have provided terminal with full access to all my files and folders. I have also tried launching python with sudo.

This is the error I receive in the manager.log file:

2021-05-12 02:26:03 [INFO]: Debug Level: INFO
2021-05-12 02:26:03 [INFO]: Chia Location: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
2021-05-12 02:26:03 [INFO]: Log Directory: /Users/[removed]/.chia/mainnet/log/swar
2021-05-12 02:26:03 [INFO]: Jobs: [{'name': 'internal', 'max_plots': 999, 'farmer_public_key': None, 'pool_public_key': None, 'temporary_directory': '/Users/[removed]/Documents/chia-nursery', 'temporary2_directory': None, 'destination_directory': '/Volumes/chia-plots-share/plots', 'size': 32, 'bitfield': True, 'threads': 4, 'buckets': 128, 'memory_buffer': 5000, 'max_concurrent': 3, 'max_concurrent_with_start_early': 2, 'stagger_minutes': 0, 'max_for_phase_1': 3, 'concurrency_start_early_phase': 4, 'concurrency_start_early_phase_delay': 10, 'temporary2_destination_sync': False}]
2021-05-12 02:26:03 [INFO]: Manager Check Interval: 60
2021-05-12 02:26:03 [INFO]: Max Concurrent: 2
2021-05-12 02:26:03 [INFO]: Progress Settings: {'phase1_line_end': 801, 'phase2_line_end': 834, 'phase3_line_end': 2474, 'phase4_line_end': 2620, 'phase1_weight': 33.4, 'phase2_weight': 20.43, 'phase3_weight': 42.29, 'phase4_weight': 3.88}
2021-05-12 02:26:03 [INFO]: Notification Settings: {'notify_discord': False, 'discord_webhook_url': 'https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'notify_sound': False, 'song': 'audio.mp3', 'notify_pushover': False, 'pushover_user_key': 'xx', 'pushover_api_key': 'xx', 'notify_twilio': False, 'twilio_account_sid': 'xxxxx', 'twilio_auth_token': 'xxxxx', 'twilio_from_phone': 1234657890, 'twilio_to_phone': 1234657890}
2021-05-12 02:26:03 [INFO]: View Settings: {'check_interval': 10, 'datetime_format': '%Y-%m-%d %H:%M:%S', 'include_seconds_for_phase': False, 'include_drive_info': True, 'include_cpu': True, 'include_ram': True, 'include_plot_stats': True}
2021-05-12 02:26:03 [INFO]: Loading jobs into objects.
2021-05-12 02:26:03 [INFO]: Grabbing running plots.
2021-05-12 02:26:03 [INFO]: Getting running plots
2021-05-12 02:26:03 [INFO]: Found chia plotting process: 28093
2021-05-12 02:26:03 [INFO]: Finding log file for process: 28093
2021-05-12 02:26:03 [INFO]: Found log file: /Users/[removed]/.chia/mainnet/plotter/plotter_log_d143342f-ac89-4381-af0d-2e848893afd5.txt
2021-05-12 02:26:03 [INFO]: Finding associated job
2021-05-12 02:26:03 [INFO]: Finished finding running plots
2021-05-12 02:26:03 [INFO]: Starting loop.
2021-05-12 02:26:03 [INFO]: Checking log progress..
2021-05-12 02:26:03 [INFO]: Checking log progress for PID: 28093
2021-05-12 02:26:03 [INFO]: PID still alive: 28093
2021-05-12 02:26:03 [INFO]: Monitoring jobs to start.
2021-05-12 02:26:03 [INFO]: Checking to queue work for job: internal
2021-05-12 02:26:03 [INFO]: Total jobs in phase 1: 0
2021-05-12 02:26:03 [INFO]: Starting new plot for job: internal
2021-05-12 02:26:03 [INFO]: Job log file path: /Users/[removed]/.chia/mainnet/log/swar/internal_2021-05-12_02_26_03_809721.log
2021-05-12 02:26:03 [INFO]: Job destination directory: /Volumes/chia-plots-share/plots
2021-05-12 02:26:03 [INFO]: Job temporary2 directory: None
2021-05-12 02:26:03 [INFO]: Starting with plot command: ['/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon', 'plots', 'create', '-k', '32', '-b', '5000', '-t', '/Users/[removed]/Documents/chia-nursery', '-d', '/Volumes/chia-plots-share/plots', '-r', '4', '-u', '128']
2021-05-12 02:26:03 [INFO]: Starting process
Traceback (most recent call last):
  File "/Users/[removed]/Documents/Swar-Chia-Plot-Manager-main/stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "/Users/[removed]/Documents/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "/Users/[removed]/Documents/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "/Users/[removed]/Documents/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon'

Also, it would be handy if the correct MacOS path was added to the config file alongside the linux and windows paths.

Finally, THANK YOU! This is exactly what I was missing in my micro farm setup!! :)

**Comment by blenbedw** [comment]
i have exactly same problem with Linux.

**Comment by AndyFromMN** [comment]
Just started using it on MacOS Catalina and was having the same error. Currently running my first plots.

Try this:
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/chia

**Comment by Jjjameson91** [comment]
Genius! That did the trick. Thank you so much! First plot started!
