### ISSUE TITLE
manager throws error on start

### ISSUE THREAD

**Issue by ramin-afshar** [swar/Swar-Chia-Plot-Manager#28]
I'm trying to run the manager on windows throws following error

```
Traceback (most recent call last):
  File "C:\Users\ramin\Swar-Chia-Plot-Manager\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\ramin\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Users\ramin\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Users\ramin\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 252, in start_process
    process = subprocess.Popen(
  File "C:\Users\ramin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ramin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\ramin\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\ramin\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType


```

**Comment by ramin-afshar** [comment]
error wars user-related. config file
