### ISSUE TITLE
manager crashed after midnight

### ISSUE THREAD

**Issue by VlaDko69** [swar/Swar-Chia-Plot-Manager#291]
Hi,

my manager crashed after midnight and I have found this log. It runs on Windows 10.

Traceback (most recent call last):
  File "C:\Users\user\Documents\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\user\Documents\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 106, in monitor_jobs_to_start
    if datetime.now() <= (start_early_date + timedelta(minutes=job.concurrency_start_early_phase_delay)):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
Traceback (most recent call last):
  File "C:\Users\user\Documents\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\user\Documents\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 106, in monitor_jobs_to_start
    if datetime.now() <= (start_early_date + timedelta(minutes=job.concurrency_start_early_phase_delay)):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'

**Comment by swar** [comment]
This is a personal issue and not an issue related with the software itself. Please use GitHub Discussions for this next time.

Your issue is also that you need to have a number value on concurrency start early phase delay. So change that value to 0 like it shows in the default file.
