### ISSUE TITLE
Manager fails to start plots

### ISSUE THREAD

**Issue by lmcke169** [swar/Swar-Chia-Plot-Manager#308]
Here is the text log for one of the files

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1256, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 34, in plots_cmd
RuntimeError: Please initialize (or migrate) your config directory with 'chia init'
[57866] Failed to execute script chia

And I will attach my config below as it is much longer.
[config.yaml.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6474621/config.yaml.txt)

Manager starts and in view says it is running but no plots are created. The log files for the plots that should have been started all say what text block seen above.

**Comment by lmcke169** [comment]
Directory of chia is confirmed to be in that location. I navigated to the location and copied the address directly while troubleshooting.

**Comment by swar** [comment]
This is a problem with your Chia app not being setup properly. I cannot help you. Please use a Discussion for this in the future. You can probably search on this repo for a solution since I'm sure someone would have mentioned it.

**Comment by lmcke169** [comment]
Was a problem with their beta installer. Had to completely reinstall chia using CLI. For anyone looking at this in the future it may be a problem with that.
