### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by kasander** [swar/Swar-Chia-Plot-Manager#32]
Hello,

I'm unable to start the manager, I've review the config file 3 times and all the paths are OK, no weird characters or spaces.

Tried in a venv, no venv, powershell, powershell admin, cmd, cmd admin. Always the same thing.

Traceback (most recent call last):
  File "C:\Users\ebilo\Documents\Swar-Chia-Plot-Manager\stateless-manager.py", line 35, in <module>
    jobs, running_work = get_running_plots(jobs, running_work)
  File "C:\Users\ebilo\Documents\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 218, in get_running_plots
    temporary2_directory=temporary2_directory)
  File "C:\Users\ebilo\Documents\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 151, in get_temp_size
    directories = [os.path.join(temporary_directory, file) for file in os.listdir(temporary_directory) if file]
  File "C:\Users\ebilo\Documents\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 151, in <listcomp>
    directories = [os.path.join(temporary_directory, file) for file in os.listdir(temporary_directory) if file]
  File "C:\Users\ebilo\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I have currently some plots running in the GUI and I gave them the same name.
Python is freshly installed on my PC and I haven't rebooted yet but the installer never said that a reboot was required.

I don't think it's an issue with your tool but I have no clue where or what to look at since all the temporary_directory are valid.

Thanks!

**Comment by swar** [comment]
@kasander  someone else had this issue and it was because another plot was running. Try the most recent changes and I think you should have better luck!

**Comment by kasander** [comment]
Ok, I'll give it a shot and I'll let you know and I'll close this. Thanks!

**Comment by kasander** [comment]
Yeah that seems better, it's now running and I guess it's going to wait for my 2 running plot to finish before taking over. I have it now open in view mode. I'll keep this open just in case something else come up when my 2 plot are done otherwise I'll close this issue tomorrow.
