### ISSUE TITLE
[BUG] manager.py view and crash every n' hours

### ISSUE THREAD

**Issue by aresstokrat** [swar/Swar-Chia-Plot-Manager#320]
on different PC's plot managers crashes. Different bugs. So i post to different issues thread.
From "manager.py view" cmd window:

Next log check at 2021-05-14 11:06:38

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\psutil\_pswindows.py", line 993, in open_files
    raw_file_names = cext.proc_open_files(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from OpenProcess -> ERROR_INVALID_PARAMETER)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\plotmanager\manager.py", line 36, in <module>
    view()
  File "c:\plotmanager\plotmanager\library\utilities\commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "c:\plotmanager\plotmanager\library\utilities\processes.py", line 203, in get_running_plots
    for file in process.open_files():
  File "C:\Program Files\Python39\lib\site-packages\psutil\__init__.py", line 1138, in open_files
    return self._proc.open_files()
  File "C:\Program Files\Python39\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=1560, name='chia.exe')

**Comment by aresstokrat** [comment]
screen http://prntscr.com/12wyafc

**Comment by LPettay** [comment]
I also seem to be having the occasional crash with `process no longer exists` across three different machines. 1x Windows and 2x Ubuntu 20.04.

**Ubuntu**
```
Next log check at 2021-05-15 17:51:43

Traceback (most recent call last):
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_common.py", line 447, in wrapper
	ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1576, in wrapper
	return fun(self, *args, **kwargs)
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_common.py", line 450, in wrapper
	return fun(self)
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
	with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_common.py", line 711, in open_binary
	return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/260568/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manager.py", line 36, in <module>
	view()
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 109, in view
	print_view(jobs=jobs, running_work=running_work, analysis=analysis, drives=drives,
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/plotmanager/library/utilities/print.py", line 114, in print_view
	drive_data = get_drive_data(drives)
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/plotmanager/library/utilities/print.py", line 92, in get_drive_data
	chia_drives = get_chia_drives()
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/plotmanager/library/utilities/processes.py", line 92, in get_chia_drives
	if chia_executable_name not in process.name() and 'python' not in process.name().lower():
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/__init__.py", line 617, in name
	name = self._proc.name()
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1576, in wrapper
	return fun(self, *args, **kwargs)
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1671, in name
	name = self._parse_stat_file()['name']
  File "/home/chia2/plotman/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1583, in wrapper
	raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=260568)
```

**Windows**
```
Traceback (most recent call last):
  File "C:\Users\Lance\PlotManager\Custom\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Lance\PlotManager\Custom\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\_pswindows.py", line 993, in open_files
    raw_file_names = cext.proc_open_files(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lance\PlotManager\Custom\Swar-Chia-Plot-Manager\manager.py", line 36, in <module>
    view()
  File "C:\Users\Lance\PlotManager\Custom\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "C:\Users\Lance\PlotManager\Custom\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 203, in get_running_plots
    for file in process.open_files():
  File "C:\Users\Lance\PlotManager\Custom\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\__init__.py", line 1138, in open_files
    return self._proc.open_files()
  File "C:\Users\Lance\PlotManager\Custom\Swar-Chia-Plot-Manager\venv\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=23064, name='chia.exe')
```

**Comment by swar** [comment]
Workaround in the development version.
