### ISSUE TITLE
can't launch the manager

### ISSUE THREAD

**Issue by 85256638** [swar/Swar-Chia-Plot-Manager#338]
C:\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "C:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 102, in get_config_info
    config = _get_config()
  File "C:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "C:\Swar-Chia-Plot-Manager-main\config.yaml", line 6, column 1

**Comment by Kenzim** [comment]
you have invalid config file syntax. google yaml syntax checker and put your config in there to check, but apparently your issue is on line 6

**Comment by swar** [comment]
This problem has been discussed many times already. Feel free to search this repo for it. Your YAML file is not configured properly. Use http://yamllint.com to double check. Please use Github Discussions next time.
