### ISSUE TITLE
[9920] Failed to execute script chia

### ISSUE THREAD

**Issue by WuYI-0x001** [swar/Swar-Chia-Plot-Manager#339]
Caught plotting error: filesystem error: cannot remove: Read-only file system [/media/wuyi/农场盘3/plot-k32-2021-05-15-01-42-29068cf3915035bb2e652ae5507d2f6417b56e5c857f161781c996b1ef5189e0.plot]
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 135, in create_cmd
  File "chia/plotting/create_plots.py", line 164, in create_plots
RuntimeError: std::exception
[9920] Failed to execute script chia

can't understand why it want to remove my readonly file and stop work

**Comment by swar** [comment]
This is a problem with Chia not with the plot manager. Please use Github Discussions next time.
