### ISSUE TITLE
Failed to start Manager W10

### ISSUE THREAD

**Issue by AmA-sud** [swar/Swar-Chia-Plot-Manager#353]
(venv) PS C:\Swar> python manager.py start
Traceback (most recent call last):
  File "C:\Swar\manager.py", line 29, in <module>
    start_manager()
  File "C:\Swar\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.

**Comment by swar** [comment]
I'm closing this. The exception literally tells you what to look at for more information.

**Comment by AmA-sud** [comment]
i have opened the file , and this is what it mentions,

Traceback (most recent call last):
  File "C:\Swar\stateless-manager.py", line 15, in <module>
    logging.basicConfig(format='%(asctime)s [%(levelname)s]: %(message)s', datefmt='%Y-%m-%d %H:%M:%S', level=debug_level)
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 2022, in basicConfig
    root.setLevel(level)
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 1421, in setLevel
    self.level = _checkLevel(level)
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'information'

I have tried to install and run the software on multiple windows 10 machines all with the same error .

sorry to bother you, but if I can debug by my self I wouldn't have asked

**Comment by swar** [comment]
Your config.yaml log_level is information? In that case, that's the problem. INFO / DEBUG / ERROR pick one of these three.
