### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by ddialer** [swar/Swar-Chia-Plot-Manager#37]
getting this error when trying to start:

PS C:\Users\user\Desktop\Swar> python manager.py start
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Swar\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\user\Desktop\Swar\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "C:\Users\user\Desktop\Swar\plotmanager\library\parse\configuration.py", line 102, in get_config_info
    config = _get_config()
  File "C:\Users\user\Desktop\Swar\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\yaml\parser.py", line 392, in parse_block_sequence_entry
    raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
  in "C:\Users\user\Desktop\Swar\config.yaml", line 134, column 3
expected <block end>, but found '<block sequence start>'
  in "C:\Users\user\Desktop\Swar\config.yaml", line 172, column 4

**Comment by stubmirror** [comment]
copy your config here, if you made changes from default it needs to have exactly same formatting i noticed, i was missing a space in my jobs and it threw a similar error.
test with default one if it works

**Comment by swar** [comment]
Yeah this one looks like a config.yaml error @ddialer Are you able to share your config? It looks like you have bad indents for the jobs sections

**Comment by DM4DS** [comment]
This happens if NO Public Key is present.

I had the same problem.

**Comment by ddialer** [comment]
attached my config. now when you said it I think the problem is inside config as well. I'll try to change it on my next restart, dont want to interupt my current plotting. Thanks guys for pointing out on the problem!

[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6409803/config.txt)

**Comment by ddialer** [comment]
it was bad indents, by mistake added extra space. thankx!
