### ISSUE TITLE
Problem with manager.py View

### ISSUE THREAD

**Issue by iFlashing** [swar/Swar-Chia-Plot-Manager#408]
> C:\Users\tuann\Downloads\swar>py manager.py view
Traceback (most recent call last):
File "C:\Users\tuann\Downloads\swar\manager.py", line 36, in
view()
File "C:\Users\tuann\Downloads\swar\plotmanager\library\utilities\commands.py", line 104, in view
analysis = analyze_log_dates(log_directory=log_directory, analysis=analysis)
File "C:\Users\tuann\Downloads\swar\plotmanager\library\utilities\log.py", line 76, in analyze_log_dates
analysis = _get_date_summary(analysis)
File "C:\Users\tuann\Downloads\swar\plotmanager\library\utilities\log.py", line 35, in _get_date_summary
end_date = analysis['files'][file_path]['data']['date'].date()
TypeError: 'bool' object is not subscriptable

Please help to fix this error. Thank you

**Comment by swar** [comment]
You're more than welcome to try to fix it. 😄

**Comment by yaotutu** [comment]
I have similar problem about the mananer.py  View when the progress running more than a day .
