### ISSUE TITLE
Cannot open the view

### ISSUE THREAD

**Issue by billybojangles** [swar/Swar-Chia-Plot-Manager#41]
I'm getting this string of errors when I attempt to run the view command.

Traceback (most recent call last):
  File "C:\plotter\Swar-Chia-Plot-Manager-main\manager.py", line 36, in <module>
    view()
  File "C:\plotter\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "C:\plotter\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 199, in get_running_plots
    for file in process.open_files():
  File "C:\plotter\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\psutil\__init__.py", line 1138, in open_files
    return self._proc.open_files()
  File "C:\plotter\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\plotter\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\psutil\_pswindows.py", line 993, in open_files
    raw_file_names = cext.proc_open_files(self.pid)
RuntimeError: SystemExtendedHandleInformation buffer too big

Any ideas?

**Comment by swar** [comment]
I can't find any good information online on this error and to me it looks like Python is requesting more memory than your computer is willing to give to it.

I added a skip to this method to skip when a RuntimeError happens, so the downside will be that your logfile will become unidentifiable since it pulls log files from that. in the future, I will look into a smarter way of guessing what a logfile is when this issue occurs.

Pull the latest changes and let me know if it fixes it as well

**Comment by billybojangles** [comment]
Thanks I'll pull the latest changes and let you know.
