### ISSUE TITLE
Manager.py start not executing

### ISSUE THREAD

**Issue by ChrisFirgaira** [swar/Swar-Chia-Plot-Manager#413]
Hey Swar,

Do you have any suggestions for the following?

I've followed the guide and upon launching cmd in administrator mode to execute manager.py I'm receiving the following error in the manager.log file

Do you think this might be related to me having installed Python 3.9.5?

Traceback (most recent call last):
  File "C:\chiaplotting\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\chiaplotting\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\chiaplotting\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\chiaplotting\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ChrisFirgaira** [comment]
Pre-emptively closing this issue, I need to research all closed issues for manager.py, my apologies, I didn't realise there had been so many raised already. Excuse me!
