### ISSUE TITLE
Plot Manager Runs but no Plots

### ISSUE THREAD

**Issue by IdontnowtheMeaning** [swar/Swar-Chia-Plot-Manager#422]
When I Start the Plot Manager it doesn't create any Plots. It says running but nothing happens, I waited now 1 hour but still nothing. Sorry for the bad English.

![Unbenannt](https://user-images.githubusercontent.com/84279920/118401585-889f6900-b666-11eb-88cb-3c6a40fb2c65.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/84279920/118401755-34e14f80-b667-11eb-9f5c-7d0e050f5a57.png)

**Comment by Falcon-Peregrine** [comment]
Same issue, with MacOS Big sur

**Comment by mmpangzi** [comment]
看一下日志，他会提示你错误的地方在哪。

**Comment by Falcon-Peregrine** [comment]
> 看一下日志，他会提示你错误的地方在哪。

The process could not find my password, I did run before with gui.

Traceback (most recent call last):
  File "keyring/backends/macOS/__init__.py", line 49, in get_password
  File "keyring/backends/macOS/api.py", line 101, in find_generic_password
  File "keyring/backends/macOS/api.py", line 48, in raise_for_status
keyring.backends.macOS.api.Error: (-25308, 'Unknown Error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 135, in create_cmd
  File "chia/plotting/create_plots.py", line 57, in create_plots
  File "chia/plotting/create_plots.py", line 28, in get_farmer_public_key
  File "chia/util/keychain.py", line 200, in get_first_private_key
  File "chia/util/keychain.py", line 142, in _get_pk_and_entropy
  File "keyring/core.py", line 55, in get_password
  File "keyring/backends/macOS/__init__.py", line 55, in get_password
keyring.errors.KeyringError: Can't get password from keychain: (-25308, 'Unknown Error')
[17903] Failed to execute script chia

**Comment by IdontnowtheMeaning** [comment]
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 55, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE

That was the information I got but I'm not really good with computers so I dont now what that means.

**Comment by dJani97** [comment]
I suggest not to use spaces and dots in your path. Name your folders like this: **Chia_Finals_M2**
Not sure if this will help, it's just a good practice in general.

**Comment by swar** [comment]
> Traceback (most recent call last):
> File "chia\cmds\chia.py", line 81, in
> File "chia\cmds\chia.py", line 77, in main
> File "click\core.py", line 829, in **call**
> File "click\core.py", line 782, in main
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1066, in invoke
> File "click\core.py", line 610, in invoke
> File "click\decorators.py", line 21, in new_func
> File "chia\cmds\plots.py", line 135, in create_cmd
> File "chia\plotting\create_plots.py", line 55, in create_plots
> ValueError: Length of bytes object not equal to G1Element::SIZE
> 
> That was the information I got but I'm not really good with computers so I dont now what that means.

This means your farmer key and/or the pool key is not the correct size.
