### ISSUE TITLE
I can't view on ubuntu20!

### ISSUE THREAD

**Issue by alex826-pex** [swar/Swar-Chia-Plot-Manager#443]
please help!
I run Swar on the ubuntu20, I have successfully run "python3 manager.py start".
run "python3 manager.py view" ,  
prompt:
Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "/home/alex/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "/home/alex/Swar-Chia-Plot-Manager/plotmanager/library/utilities/processes.py", line 221, in get_running_plots
    if destination_directory not in job.destination_directory:
TypeError: argument of type 'NoneType' is not iterable

**Comment by swar** [comment]
Bad config. Looks like you dont have destination directories for one of your jobs.
