### ISSUE TITLE
error wont start.

### ISSUE THREAD

**Issue by ddijanic** [swar/Swar-Chia-Plot-Manager#448]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\Swar-Chia-Plot-Manager\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\lenovo\Documents\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Users\lenovo\Documents\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Users\lenovo\Documents\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

setings. 

  - name: DD
    max_plots: 20
    farmer_public_key: a958c36a313157d6d7625ae8422bfe84cfb3e9c07918c602fa0475e6df2439e38f91ab842309db6105d96b04d072c9bf
    pool_public_key: 84c3bc5e613136d0ea295b8aa4c429db117700d007e20fb92b498bb0feb079515cc6f460619693c6e364dc1a84582407
    temporary_directory: C:\chia temp
    destination_directory: D:\chia1
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 3400
    max_concurrent: 1
    max_concurrent_with_start_early: 2
    stagger_minutes: 60
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

**Comment by swar** [comment]
Wrong chia_location or you dont have a space after the colon
