### ISSUE TITLE
Manager fails after start with psutil error

### ISSUE THREAD

**Issue by laroyru** [swar/Swar-Chia-Plot-Manager#484]
Restarting view due to psutil going stale...
Traceback (most recent call last):
  File "manager.py", line 4, in <module>
    from plotmanager.library.utilities.commands import start_manager, stop_manager, view, analyze_logs
  File "/home/farmer/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

although psutil is installed

Requirement already satisfied: psutil in ./venv/lib/python3.8/site-packages (5.8.0)

Ubuntu 20.04.2 LTS

**Comment by swar** [comment]
Use `pip3` and `python3`
