### ISSUE TITLE
skip_full_destinations error with UNC as destination

### ISSUE THREAD

**Issue by onedpb** [swar/Swar-Chia-Plot-Manager#500]
This feature seems not to work with an UNC path as destination drive.

I have "destination_directory: \\nas\farm" in my config-yaml. When starting "manager.py view" I get this error:

Traceback (most recent call last):
  File "C:\plotmanager\manager.py", line 37, in <module>
    view()
  File "C:\plotmanager\plotmanager\library\utilities\commands.py", line 167, in view
    print_view(jobs=jobs, running_work=running_work, analysis=analysis, drives=drives,
  File "C:\plotmanager\plotmanager\library\utilities\print.py", line 195, in print_view
    drive_data = get_drive_data(drives, running_work, job_data)
  File "C:\plotmanager\plotmanager\library\utilities\print.py", line 149, in get_drive_data
    usage = psutil.disk_usage(drive)
  File "C:\Users\xxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\xxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None

When using a local drive letter (like E:\) it works.

**Comment by swar** [comment]
Try version 0.1.0 to see if it fixes your issues.
https://github.com/swar/Swar-Chia-Plot-Manager/releases/tag/v.0.1.0
