### ISSUE TITLE
[BUG] psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=610796)

### ISSUE THREAD

**Issue by rmokerone** [swar/Swar-Chia-Plot-Manager#509]
```
Next log check at 2021-05-18 02:24:33

Traceback (most recent call last):
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/610796/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/plotmanager/library/utilities/processes.py", line 178, in get_running_plots
    if chia_executable_name not in process.name() and 'python' not in process.name().lower():
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/__init__.py", line 617, in name
    name = self._proc.name()
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1671, in name
    name = self._parse_stat_file()['name']
  File "/home/ctestp/Coding/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1583, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=610796)
```

**Comment by wackywavytube** [comment]
this just happened to me too. can't stop, start, or view manager.py

**Comment by swar** [comment]
Try version 0.1.0 to see if it fixes your issue.
https://github.com/swar/Swar-Chia-Plot-Manager/releases/tag/v.0.1.0
