### ISSUE TITLE
Run python manager.py start, can’t start, please help me

### ISSUE THREAD

**Issue by Tiexcn** [swar/Swar-Chia-Plot-Manager#522]
(chia) E:\Tools\Swar-Chia-Plot-Manager>python manager.py start
Traceback (most recent call last):
  File "E:\Tools\Swar-Chia-Plot-Manager\manager.py", line 29, in <module>
    start_manager()
  File "E:\Tools\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "E:\Tools\Swar-Chia-Plot-Manager\plotmanager\library\parse\configuration.py", line 102, in get_config_info
    config = _get_config()
  File "E:\Tools\Swar-Chia-Plot-Manager\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "E:\Tools\Swar-Chia-Plot-Manager\chia\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "E:\Tools\Swar-Chia-Plot-Manager\config.yaml", line 136, column 5
could not find expected ':'
  in "E:\Tools\Swar-Chia-Plot-Manager\config.yaml", line 137, column 5

(chia) E:\Tools\Swar-Chia-Plot-Manager>

-------------------

config.yaml 

 - name: micron
    max_plots: 999
    farmer_public_key:*******************
    pool_public_key:*******************
    temporary_directory: D:\Chia_Cacha
    temporary2_directory:
    destination_directory: F:\Chia
    size: 32
    bitfield: true
    threads: 4
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 1
    max_concurrent_with_start_early: 7
    stagger_minutes: 1
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

**Comment by r1235613** [comment]
You need spare between `:` and `key`
```
farmer_public_key: *******************
pool_public_key: *******************
```

**Comment by Shadehand** [comment]
Hi, same issue here. I did the homework from the install description and i got this: 

c:\Users\Chia\PM>py manager.py start
Traceback (most recent call last):
  File "c:\Users\Chia\PM\manager.py", line 29, in <module>
    start_manager()
  File "c:\Users\Chia\PM\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.

**_LOG FILE:_**

Traceback (most recent call last):
  File "C:\Users\Chia\PM\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\Chia\PM\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Users\Chia\PM\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Users\Chia\PM\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Users\Chia\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Chia\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by Tiexcn** [comment]
> You need spare between `:` and `key`
> 
> ```
> farmer_public_key: *******************
> pool_public_key: *******************
> ```

Thank you very much, my problem has been solved according to your tips.

**Comment by Tiexcn** [comment]
> Hi, same issue here. I did the homework from the install description and i got this:
> (i run it from cmd as admin)
> 
> c:\Users\Chia\PM>py manager.py start
> Traceback (most recent call last):
>   File "c:\Users\Chia\PM\manager.py", line 29, in
>     start_manager()
>   File "c:\Users\Chia\PM\plotmanager\library\utilities\commands.py", line 47, in start_manager
>     raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
> plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.
> 
> **_LOG FILE:_**
> 
> Traceback (most recent call last):
>   File "C:\Users\Chia\PM\stateless-manager.py", line 58, in
>     jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
>   File "C:\Users\Chia\PM\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
>     job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
>   File "C:\Users\Chia\PM\plotmanager\library\utilities\jobs.py", line 169, in start_work
>     process = start_process(args=plot_command, log_file=log_file)
>   File "C:\Users\Chia\PM\plotmanager\library\utilities\processes.py", line 276, in start_process
>     process = subprocess.Popen(
>   File "C:\Users\Chia\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in **init**
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Chia\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> PermissionError: [WinError 5] Access is denied

You can check the 2L solution. Check if you need spaces,

**Comment by Shadehand** [comment]
i did not write any key there, i use as deafault

**Comment by Shadehand** [comment]
- name: SAMSUNG 970 pro 1Tb
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: e:\
    temporary2_directory:
    destination_directory: d:\
    size: 32
    bitfield: true
    threads: 6
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    stagger_minutes: 60
    max_for_phase_1: 3
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
