### ISSUE TITLE
psutil Access Denied when starting the manager

### ISSUE THREAD

**Issue by Exzellenz** [swar/Swar-Chia-Plot-Manager#531]
Hi i got  the great Plotmanager now running on 3 other Pcs but when i want to start it on my other Pc i get this output:

```
Traceback (most recent call last):
  File "C:\Users\p.anderl\plotman\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\p.anderl\plotman\Swar\venv\lib\site-packages\psutil\_common.py", line 450, in wrapper
    return fun(self)
  File "C:\Users\p.anderl\plotman\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] Das Programm hat einen Befehl ausgegeben, aber die Befehlslänge ist falsch: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\p.anderl\plotman\Swar\plotmanager\library\utilities\commands.py", line 20, in start_manager
    if get_manager_processes():
  File "C:\Users\p.anderl\plotman\Swar\plotmanager\library\utilities\processes.py", line 30, in get_manager_processes
    if not re.search(r'^pythonw?(?:\d+\.\d+|\d+)?(?:\.exe)?$', process.name(), flags=re.I):
  File "C:\Users\p.anderl\plotman\Swar\venv\lib\site-packages\psutil\__init__.py", line 617, in name
    name = self._proc.name()
  File "C:\Users\p.anderl\plotman\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "C:\Users\p.anderl\plotman\Swar\venv\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=1936) 
```
i tried in venv without venv, in powershell and cmd  as admin and non admin. it would be great if someone could tell me what i can do  in this matter. 
Thank you

**Comment by TonyAntoni** [comment]
i got same problem and dont know how to solve it

**Comment by Exzellenz** [comment]
i was able to start the stateless-manager.py but ofc it would be much better to have the overview can only assume that it wants to access an invalid pid?

**Comment by Shadehand** [comment]
Hi, same issue here. I did the homework from the install description and i got this:
(i run it from cmd as admin)

c:\Users\Chia\PM>py manager.py start
Traceback (most recent call last):
  File "c:\Users\Chia\PM\manager.py", line 29, in
    start_manager()
  File "c:\Users\Chia\PM\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.

LOG FILE:

Traceback (most recent call last):
  File "C:\Users\Chia\PM\stateless-manager.py", line 58, in
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\Chia\PM\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Users\Chia\PM\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Users\Chia\PM\plotmanager\library\utilities\processes.py", line 276, in start_process
    process = subprocess.Popen(
  File "C:\Users\Chia\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Chia\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

Config:

name: SAMSUNG 970 pro 1Tb
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: e:
    temporary2_directory:
    destination_directory: d:
    size: 32
    bitfield: true
    threads: 6
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    stagger_minutes: 60
    max_for_phase_1: 3
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

**Comment by cojarbi** [comment]
Did you run the environment before running the manager?

Activate the virtual environment. This must be done every single time you open a new window.
Example Windows: venv\Scripts\activate

**Comment by Exzellenz** [comment]
> Did you run the environment before running the manager?
> 
> Activate the virtual environment. This must be done every single time you open a new window.
> Example Windows: venv\Scripts\activate

Yes like i said i tried it  with and without enviroment and also created the enviroment new. but without success.

**Comment by cojarbi** [comment]
I was having all those problem, after making sure python was correctly installed and in PATH, i jsut deleted the swar folder and started fro mzero

**Comment by Shadehand** [comment]
I have deleted my post. It was my fault. I have checked another tutorial and i have found my error.
It was the chia path in config file

**Comment by swar** [comment]
Try version 0.1.0 to see if it fixes your issue.
https://github.com/swar/Swar-Chia-Plot-Manager/releases/tag/v.0.1.0
