### ISSUE TITLE
Issue reading drive information

### ISSUE THREAD

**Issue by gazaz** [swar/Swar-Chia-Plot-Manager#555]
I'm using the development version and there seems to be an issue reading the drive information.

If I set skip full destinations to true, the script won't start and gives this error .....

2021-05-19 09:15:11 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\Swar\plotmanager\library\utilities\jobs.py", line 163, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\Python39\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Python39\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\Swar\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Swar\plotmanager\library\utilities\jobs.py", line 248, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Swar\plotmanager\library\utilities\jobs.py", line 274, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\Swar\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\Swar\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\Swar\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType

If I disable set skip full destinations to false it starts ok , but I am unable to view the script running unless I set include_dive_info: to false. If it is set to true I get this error.

Traceback (most recent call last):
  File "C:\Swar\manager.py", line 37, in <module>
    view()
  File "C:\Swar\plotmanager\library\utilities\commands.py", line 167, in view
    print_view(jobs=jobs, running_work=running_work, analysis=analysis, drives=drives,
  File "C:\Swar\plotmanager\library\utilities\print.py", line 195, in print_view
    drive_data = get_drive_data(drives, running_work, job_data)
  File "C:\Swar\plotmanager\library\utilities\print.py", line 149, in get_drive_data
    usage = psutil.disk_usage(drive)
  File "C:\Python39\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Python39\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None

My temp directory is local, but my destinaton is an smb share on my MAS   \\NAS\folder

**Comment by onedpb** [comment]
Works when you mount your smb share to a drive letter in Windows.
