### ISSUE TITLE
how can my cpu have useage above 100%?

### ISSUE THREAD

**Issue by puka89** [swar/Swar-Chia-Plot-Manager#564]
Log file:
`Starting plotting progress into temporary dirs: G:\ and G:\
ID: 43b844dacf3e190a3c260f1f20b64d562d6c5d8636582b6e173e76e844ad5d4c
Plot size is: 32
Buffer size is: 4000MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Wed May 19 05:18:52 2021
Computing table 1
F1 complete, time: 151.046 seconds. CPU (134.71%) Wed May 19 05:21:23 2021
Computing table 2
Caught plotting error: bad allocation
[12244] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation
`

**Comment by Lyushen** [comment]
That percentage shows multithreading. Like 3 threads = 300%. You need to track this value after each phase to find best thread-in-config value. For me 4 threads is the best.
Bad allocation means u out of ram. For tracking out of memory usage, u actually can't do it with the windows task manager. For that porpuses I recommend you to run HWiNFO sensors and track the "Virtual Memory Load". This is real usage of your RAM.
