### ISSUE TITLE
Can t start

### ISSUE THREAD

**Issue by hugosdivaca** [swar/Swar-Chia-Plot-Manager#582]
My log:

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1256, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 34, in plots_cmd
RuntimeError: Please initialize (or migrate) your config directory with 'chia init'
[88735] Failed to execute script chia

my chia path: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia

Can u help me guys. I rly don t get where the problem is. Thanks for help.

**Comment by swar** [comment]
Try version 0.1.0 to see if it fixes your issues.
https://github.com/swar/Swar-Chia-Plot-Manager/releases/tag/v.0.1.0
