### ISSUE TITLE
manager.py throwing psutil.AccessDenied with start_harvester.exe running

### ISSUE THREAD

**Issue by rijulluman** [swar/Swar-Chia-Plot-Manager#583]
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psutil\_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psutil\_common.py", line 450, in wrapper
    return fun(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] The program issued a command but the command length is incorrect: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "C:\Users\User\Desktop\Swar1\plotmanager\library\utilities\commands.py", line 109, in view
    print_view(jobs=jobs, running_work=running_work, analysis=analysis, drives=drives,
  File "C:\Users\User\Desktop\Swar1\plotmanager\library\utilities\print.py", line 116, in print_view
    manager_processes = get_manager_processes()
  File "C:\Users\User\Desktop\Swar1\plotmanager\library\utilities\processes.py", line 30, in get_manager_processes
    if not re.search(r'^pythonw?(?:\d+\.\d+|\d+)?(?:\.exe)?$', process.name(), flags=re.I):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psutil\__init__.py", line 617, in name
    name = self._proc.name()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=11020)
```
Here 11020 was start_harvester.exe
Also I am using Windows 10 and ran cmd as Admin

**Comment by rijulluman** [comment]
All the chia.exe instances are running in the background, but the view does not load when the harvester is running in the background. Also I think once the already scheduled plotting tasks complete the manager will throw an exception while trying to create a new plotter instance.

**Comment by swar** [comment]
Try version 0.1.0 to see if it fixes your issues.
https://github.com/swar/Swar-Chia-Plot-Manager/releases/tag/v.0.1.0
