### ISSUE TITLE
Failed to start the manager - Failed to get disk_usage of drive None

### ISSUE THREAD

**Issue by kaktus79** [swar/Swar-Chia-Plot-Manager#628]
Hi,

  I have a problem with starting the manager v0.1.0 (debug.log below). Worked fine in previous version.

2021-05-20 13:59:44 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\Chia\scripts\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\Users\Użytkownik\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\Użytkownik\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\Chia\scripts\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Chia\scripts\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Chia\scripts\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 284, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\Chia\scripts\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\Chia\scripts\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\Chia\scripts\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by dkimmortal** [comment]
Got the same issue

**Comment by master-merlin** [comment]
+1

**Comment by pernahajder** [comment]
in config.yaml set the temp and destination dirs as list:
for example:
    temporary_directory:
        - Y:\
    destination_directory:
        - Z:\ChiaFarm

**Comment by master-merlin** [comment]
> in config.yaml set the temp and destination dirs as list:
> for example:
> temporary_directory:
> - Y:
> destination_directory:
> - Z:\

This starts the manager however, it does not spawn new tasks, debug log:
2021-05-20 17:38:21 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "D:\Mining\Swar-Chia-Plot-Manager-v.0.1.0\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "d:\Mining\Swar-Chia-Plot-Manager-v.0.1.0\chia\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "d:\Mining\Swar-Chia-Plot-Manager-v.0.1.0\chia\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None

**Comment by pernahajder** [comment]
capitalization matters for dirs, drive letter is always capital char.
if you have set a folder, try to set/remove the trailing "\"

**Comment by master-merlin** [comment]
> capitalization matters for dirs, drive letter is always capital char.
> if you have set a folder, try to set/remove the trailing backslash

This solved it for me. For less experienced users upper() and replace() last instance of \ might help.

**Comment by kaktus79** [comment]
> capitalization matters for dirs, drive letter is always capital char.

It helped, thank you.

**Comment by Alijambo** [comment]
Same problem.  Drives are capitalized and the network drive is mounted.

temporary_directory: Z:\LAPTOPTEMP
    temporary2_directory: 
    destination_directory: G:\LaptopChiaPlots

**Comment by pernahajder** [comment]
> 
> 
> Same problem. Drives are capitalized and the network drive is mounted.
> 
> temporary_directory: Z:\LAPTOPTEMP
> temporary2_directory:
> destination_directory: G:\LaptopChiaPlots

try this way:
temporary_directory:
 - Z:\LAPTOPTEMP
temporary2_directory:
destination_directory:
 - G:\LaptopChiaPlots

**Comment by Rekternino** [comment]
I tried every options but still same problem

**Comment by Rekternino** [comment]
I think chia gui is okay. This problem is waste of time and energy.

**Comment by kaktus79** [comment]
> I think chia gui is okay. This problem is waste of time and energy.

The issue is not about the Chia GUI and it is already closed.

**Comment by Alijambo** [comment]
> > Same problem. Drives are capitalized and the network drive is mounted.
> > temporary_directory: Z:\LAPTOPTEMP
> > temporary2_directory:
> > destination_directory: G:\LaptopChiaPlots
> 
> try this way:
> temporary_directory:
> - Z:\LAPTOPTEMP
> temporary2_directory:
> destination_directory:
> - G:\LaptopChiaPlots
I tried that too nothing seems to work.
