### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'S:\\'

### ISSUE THREAD

**Issue by Zipties** [swar/Swar-Chia-Plot-Manager#632]
I get this error when I try to run the plotter. I have been through the config files and I cannot find any reference to S:\\

`C:\Program Files\SwarPlotManager>python manager.py start
Traceback (most recent call last):
  File "C:\Program Files\SwarPlotManager\manager.py", line 30, in <module>
    start_manager()
  File "C:\Program Files\SwarPlotManager\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "C:\Program Files\SwarPlotManager\plotmanager\library\parse\configuration.py", line 143, in get_config_info
    os.makedirs(log_directory)
  File "C:\Program Files\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'S:\\'`

**Comment by andyquek** [comment]
You’re suppose to change it to the name of the drive you have. Change it to C:\ as I can see you have a C drive on your computer. 

It should solve the issue

**Comment by Zipties** [comment]
I figured it out. The config file doesn't like UNC paths.

**Comment by sergeyhakalo** [comment]
> I figured it out. The config file doesn't like UNC paths.

May you please clarify how you have fixed this problem?
Have exactly the same issue.

**Comment by Zipties** [comment]
> > I figured it out. The config file doesn't like UNC paths.
> 
> May you please clarify how you have fixed this problem?
> Have exactly the same issue.

If I used a //UNV path I got the weird error about an S:// drive. 

I mapped a network drive and changes it from UNC to a drive letter path. But, apparently the latest with does patch breaks network drives too.

**Comment by lsHaKeRl** [comment]
Hi Dude! You have to look at the config.yaml file, there is a PATH for your LOGFILES, you have to change this PATH, the standard is S:/ in it, change it, then it would be SOLVED.

Greetings Patrick :)
