### ISSUE TITLE
File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\manager.py", line 42, in <module>

### ISSUE THREAD

**Issue by morgado198028** [swar/Swar-Chia-Plot-Manager#635]
C:\Users\Chia\Swar-Chia-Plot-Manager-main>python manager.py status
Traceback (most recent call last):
  File "C:\Users\Chia\Swar-Chia-Plot-Manager-main\manager.py", line 42, in <module>
    raise InvalidArgumentException(error_message)
plotmanager.library.utilities.exceptions.InvalidArgumentException: Invalid action provided. The valid options are "start", "restart", "stop", "view", and "analyze_logs".

**Comment by tritechnik** [comment]
"The valid options are "start", "restart", "stop", "view", and "analyze_logs"." Status isn't in that list.
