### ISSUE TITLE
psutil.AccessDenied - Manager stops after adding a job to the queue (Linux)

### ISSUE THREAD

**Issue by vikar123** [swar/Swar-Chia-Plot-Manager#638]
Hi! 

I get the following error after the manager adds another job to the queue and I have to manually start the manager again.
The job starts fine, I just have to manually restart the manager for it to add another job to the queue.

I get a permission denied, but I don't understand where?

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kapsy/Swar-Chia-Plot-Manager-main/stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "/home/kapsy/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "/home/kapsy/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/jobs.py", line 327, in start_work
    psutil.Process(pid).nice(nice_val)
  File "/usr/local/lib/python3.9/dist-packages/psutil/__init__.py", line 724, in nice
    self._proc.nice_set(value)
  File "/usr/local/lib/python3.9/dist-packages/psutil/_pslinux.py", line 1578, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=39404)

**Comment by vikar123** [comment]
Ah, It's possible its due to the unix_process_priority. Is it safe to comment out this?

**Comment by vikar123** [comment]
Commenting out this works. Now it keeps on plotting. I'll leave this up for others to see. Maybe you need sudo?

#unix_process_priority: 0
#windows_process_priority: 32

**Comment by fabriziocacicia** [comment]
I'm having the same issue after upgrading to 0.1.0

```
Traceback (most recent call last):
  File "/home/chia/Swar-Chia-Plot-Manager/swar/lib/python3.8/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/chia/Swar-Chia-Plot-Manager/swar/lib/python3.8/site-packages/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chia/Swar-Chia-Plot-Manager/stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "/home/chia/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "/home/chia/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 327, in start_work
    psutil.Process(pid).nice(nice_val)
  File "/home/chia/Swar-Chia-Plot-Manager/swar/lib/python3.8/site-packages/psutil/__init__.py", line 724, in nice
    self._proc.nice_set(value)
  File "/home/chia/Swar-Chia-Plot-Manager/swar/lib/python3.8/site-packages/psutil/_pslinux.py", line 1578, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2262)
```

**Comment by qihuazhong** [comment]
Having the same issue after upgrading to 0.1.0. This should be a priority to be fixed.


Commenting the unix_process_priority line works as a temp fix for me, but new plots would start with a "very low" priority when I comment out that line.

**Comment by j4r3kb** [comment]
It happens on first ever try, second time it works for me:

```
(swar) jarek@tna:~/swar$ python3 manager.py start
Traceback (most recent call last):
  File "manager.py", line 30, in <module>
    start_manager()
  File "/home/jarek/swar/plotmanager/library/utilities/commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.
(swar) jarek@tna:~/swar$ cat debug.log 
Traceback (most recent call last):
  File "/home/jarek/swar/swar/lib/python3.8/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/jarek/swar/swar/lib/python3.8/site-packages/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jarek/swar/stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "/home/jarek/swar/plotmanager/library/utilities/jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "/home/jarek/swar/plotmanager/library/utilities/jobs.py", line 327, in start_work
    psutil.Process(pid).nice(nice_val)
  File "/home/jarek/swar/swar/lib/python3.8/site-packages/psutil/__init__.py", line 724, in nice
    self._proc.nice_set(value)
  File "/home/jarek/swar/swar/lib/python3.8/site-packages/psutil/_pslinux.py", line 1578, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=19143)
(swar) jarek@tna:~/swar$ python3 manager.py start
Plot Manager has started...
```
