### ISSUE TITLE
python manager.py start = syntax error

### ISSUE THREAD

**Issue by th3gamingfreaks** [swar/Swar-Chia-Plot-Manager#64]
been trying to figure this out for about a day now ive done a bunch of stuff with reinstalling, setting python to paths and just not sure 
![swar](https://user-images.githubusercontent.com/46638370/116820085-23655700-ab41-11eb-98f1-7b8f3eb32d21.png)

**Comment by dutchgecko** [comment]
Try running `python3 manager.py start`

It looks like your default python is python2.

**Comment by th3gamingfreaks** [comment]
> Try running `python3 manager.py start`
> 
> It looks like your default python is python2.


when i do python 3 i get this    

`gamer@gamerpc:~/Swar-Chia-Plot-Manager$` python3 manager.py start
Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "/home/gamer/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "/home/gamer/Swar-Chia-Plot-Manager/plotmanager/library/parse/configuration.py", line 102, in get_config_info
    config = _get_config()
  File "/home/gamer/Swar-Chia-Plot-Manager/plotmanager/library/parse/configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/gamer/.local/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/home/gamer/Swar-Chia-Plot-Manager/config.yaml", line 6, column 1
expected <block end>, but found '<block sequence start>'
  in "/home/gamer/Swar-Chia-Plot-Manager/config.yaml", line 154, column 2
gamer@gamerpc:~/Swar-Chia-Plot-Manager$ 
`
here is my config 
[config (copy).txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6411968/config.copy.txt)

**Comment by dutchgecko** [comment]
On line 154 you should have two spaces before the `-`, there's currently only one.

There doesn't seem to be a problem with line 6, but that error seems similar to #58. Can you try fixing line 154 and see if that fixes the config?

**Comment by th3gamingfreaks** [comment]
i love you thank you so much @dutchgecko

**Comment by swar** [comment]
Thanks for your help @dutchgecko
