### ISSUE TITLE
Error: Failed to get disk_usage of drive None. please help.

### ISSUE THREAD

**Issue by kittinzaa** [swar/Swar-Chia-Plot-Manager#654]
logs

2021-05-21 03:47:53 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\Users\tle_s\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\Program Files\Python39\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Program Files\Python39\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\Users\tle_s\Desktop\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\tle_s\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Users\tle_s\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 284, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\Users\tle_s\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\Users\tle_s\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\Users\tle_s\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType

---

Preset Settings

- name: MP510 Raid 0
    max_plots: 999
    farmer_public_key: XXXXXXXX
    pool_public_key: XXXXXXXX
    temporary_directory: G:\
    temporary2_directory:
    destination_directory: \\192.168.2.20\plot1_red4tb\Plots
    size: 32
    bitfield: true
    threads: 5
    buckets: 128
    memory_buffer: 5000
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    initial_delay_minutes: 0
    stagger_minutes: 45
    max_for_phase_1: 4
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 16384
    enable_cpu_affinity: enable
    cpu_affinity: [ 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]

**Comment by kittinzaa** [comment]
I have fixed this by maped network drive to windows and use normal directory format.
