### ISSUE TITLE
Not sure what's happening - any help ?

### ISSUE THREAD

**Issue by kushmoke** [swar/Swar-Chia-Plot-Manager#67]
`python : Traceback (most recent call last):
At line:1 char:1
+ python manager.py start
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\Python 385\lib\site-packages\psutil\_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python 385\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python 385\lib\site-packages\psutil\_common.py", line 450, in wrapper
    return fun(self)
  File "C:\Python 385\lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] The program issued a command but the command length is incorrect: '(originated from NtQuerySystemInformation)'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\Joey_\Desktop\PlotManager\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 20, in start_manager
    if get_manager_processes():
  File "C:\Users\Joey_\Desktop\PlotManager\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\processes.py", line 30, in get_manager_processes
    if not re.search(r'^pythonw?(?:\d+\.\d+|\d+)?(?:\.exe)?$', process.name(), flags=re.I):
  File "C:\Python 385\lib\site-packages\psutil\__init__.py", line 617, in name
    name = self._proc.name()
  File "C:\Python 385\lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "C:\Python 385\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=984)`

**Comment by dnknitro** [comment]
How did you fix it?
