### ISSUE TITLE
Hello, looking for help for adding Farm and Pool keys, error [3024] Failed to execute script chia

### ISSUE THREAD

**Issue by userbox020** [swar/Swar-Chia-Plot-Manager#675]
Im trying to use hpool but for some reason it says my farm and pool keys are wrong

[3024] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 55, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE

**Comment by rackommended** [comment]
I have same problem:

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 135, in create_cmd
  File "chia/plotting/create_plots.py", line 64, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE
[2998] Failed to execute script chia

**Comment by MatejBajzeljGreyMatters** [comment]
You are probably adding pool and farmer key you get from hpool app. this is wrong, you include your farmer and pool key. I tested this and it's working and I get paid.

**Comment by rackommended** [comment]
> You are probably adding pool and farmer key you get from hpool app. this is wrong, you include your farmer and pool key. I tested this and it's working and I get paid.

thx, it's working.

**Comment by shmox75** [comment]
> You are probably adding pool and farmer key you get from hpool app. this is wrong, you include your farmer and pool key. I tested this and it's working and I get paid.

Can you please elaborate because I'm stuck with unsigned plots. Which farmer & pool key should I include ? the ones generated with hpool plotter ? or from chia gui app ? Thanks
