### ISSUE TITLE
Can't work, please help me ，Think

### ISSUE THREAD

**Issue by Tiexcn** [swar/Swar-Chia-Plot-Manager#679]
(chia) C:\Users\Administrator\Desktop\Swar-Chia-Plot-Manager>python manager.py start
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Swar-Chia-Plot-Manager\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\Administrator\Desktop\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.

I don't know what went wrong

**Comment by GAMEBOOK** [comment]
Same issue here

**Comment by JayPark777** [comment]
Didn't you update it to 1.1.6? Change the chia path in config.yaml.

chia_location: C:\Users\ [username] \AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe

**Comment by Tiexcn** [comment]
> Same issue here. Do you have a debug.log file empty (mine is empty) ?
> #676
`Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Swar-Chia-Plot-Manager\stateless-manager.py", line 84, in <module>
    while has_active_jobs_and_work(jobs):
  File "C:\Users\Administrator\Desktop\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 16, in has_active_jobs_and_work
    if job.total_kicked_off < job.max_plots:
TypeError: '<' not supported between instances of 'int' and 'str'
`

**Comment by Tiexcn** [comment]
> Same issue here. Do you have a debug.log file empty (mine is empty) ?
> #676

“max_plots: AAA“    Something went wrong here 。。。。
