### ISSUE TITLE
Unable to start plot manager after upgrade

### ISSUE THREAD

**Issue by Delerium69** [swar/Swar-Chia-Plot-Manager#682]
Upgrade to Development Version: v0.1.0

Error:

```
Traceback (most recent call last):
  File "D:\Program Files\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "D:\Program Files\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "D:\Program Files\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 145, in get_config_info
    max_concurrent, max_for_phase_1, minimum_minutes_between_jobs = _get_global_config(config=config)
  File "D:\Program Files\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 62, in _get_global_config
    _check_parameters(parameter=global_config, expected_parameters=expected_parameters, parameter_type='global')
  File "D:\Program Files\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 133, in _check_parameters
    raise InvalidYAMLConfigException(f'Failed to find the following {parameter_type} parameters: '
plotmanager.library.utilities.exceptions.InvalidYAMLConfigException: Failed to find the following global parameters: max_for_phase_1, minimum_minutes_between_jobs
```

[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6522254/config.txt)

config.yaml attached as config.txt

**Comment by Delerium69** [comment]
Seeem to have resolved it by copying over the same installation from another plotter machine... very strange
