### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by DonCamillo123** [swar/Swar-Chia-Plot-Manager#685]
I got this ERROR Message, can anyone help me ? 

PS C:\Users\Patrik\Swar-Chia-Plot-Manager-main> python manager.py start
Traceback (most recent call last):
  File "C:\Users\Patrik\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\Patrik\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 39, in start_manager
    test_configuration(chia_location=chia_location, notification_settings=notification_settings,
  File "C:\Users\Patrik\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\configuration.py", line 7, in test_configuration
    if not os.path.exists(chia_location):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
PS C:\Users\Patrik\Swar-Chia-Plot-Manager-main>

**Comment by JayPark777** [comment]
Didn't you update it to 1.1.6? Change the chia path in config.yaml.

chia_location: C:\Users\ [username] \AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe

**Comment by DonCamillo123** [comment]
Ah ok my fault i updated and it was on 1.1.5 on the Config , changed it to 1.1.6 now it works ;) thanks a lot
