### ISSUE TITLE
Can't start manager ! help me please 

### ISSUE THREAD

**Issue by MiaPandy** [swar/Swar-Chia-Plot-Manager#696]
Can't start manager ! help me please 
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 138, in get_config_info
    config = _get_config()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\config.yaml", line 178, column 14
(venv) PS C:\Users\Admin\Desktop\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main>

**Comment by JayPark777** [comment]
Didn't you update it to 1.1.6? Change the chia path in config.yaml.

chia_location: C:\Users\JayPark\AppData\Local\chia-blockchain\app-**1.1.6**\resources\app.asar.unpacked\daemon\chia.exe

**Comment by MiaPandy** [comment]
> Didn't you update it to 1.1.6? Change the chia path in config.yaml.
> 
> chia_location: C:\Users\ [username] \AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe

Hi! Thanks you for support !
However I have changed correct when updated, It's still can't work, i don't know why....
