### ISSUE TITLE
Network disk is not supported

### ISSUE THREAD

**Issue by BryanXBY** [swar/Swar-Chia-Plot-Manager#707]
Can you support network mapped disks?
[ERROR]: Failed to get disk_usage of drive None.

**Comment by Zipties** [comment]
Works for me

**Comment by star250** [comment]
Me too.

2021-05-22 02:18:21 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\venv\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\venv\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\plotmanager\library\utilities\jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\plotmanager\library\utilities\jobs.py", line 284, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\Users\stars\Swar-Chia-Plot-Manager-v.0.1.0\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by alewir** [comment]
I have same error as above under Windows.
No matter if I'll use mapped drive letter, eg. `L:\` or IP location of the samba share, like `\\192.168.1.145\` the result is always as in comment above `TypeError: 'in ' requires string as left operand, not NoneType`.

**Comment by onrozcn** [comment]
same error for me to.

[ERROR]: Failed to get disk_usage of drive None.

**Comment by fufar** [comment]
same for me

**Comment by star250** [comment]
I use a temporary solution.
First, use the local disk, run this program.
Then modify the disk character to map to the remote URL.

**Comment by BryanXBY** [comment]
Can this display the remaining disk space?

**Comment by BryanXBY** [comment]
> 
> 
> I use a temporary solution.
> First, use the local disk, run this program.
> Then modify the disk character to map to the remote URL.
Can this display the remaining disk space?

**Comment by BryanXBY** [comment]
> 
> 
> I use a temporary solution.
> First, use the local disk, run this program.
> Then modify the disk character to map to the remote URL.

Can this display the remaining disk space?
