### ISSUE TITLE
Unable to Start Manager - Issue with Job Size Calculation

### ISSUE THREAD

**Issue by bmeutzner** [swar/Swar-Chia-Plot-Manager#713]
Traceback (most recent call last):
  File "C:\Users\XXX XXX\Documents\GitHub\Swar-Chia-Plot-Manager\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\XXX XXX\Documents\GitHub\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 185, in monitor_jobs_to_start
    work_size = determine_job_size(work.k_size)
  File "C:\Users\XXX XXX\Documents\GitHub\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 147, in determine_job_size
    k_size = int(k_size)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by bmeutzner** [comment]
SOLVED: I was attempting to start the manager and still had plots running with through Chia CLI... once those were closed out Manager starts correctly.
