### ISSUE TITLE
Failed to find the following global parameters: max_for_phase_1, minimum_minutes_between_jobs

### ISSUE THREAD

**Issue by adamsky-01** [swar/Swar-Chia-Plot-Manager#716]
What's wrong ??
My config in config.yaml:

```
  - name: Transcend_2TB
    max_plots: 12
    farmer_public_key:
    pool_public_key:
    temporary_directory: P:\temp
    temporary2_directory:
    destination_directory: S:\
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 3400
    max_concurrent: 5
    max_concurrent_with_start_early: 6
    stagger_minutes: 60
    max_for_phase_1: 3
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
```
```
(venv) PS D:\chia\Swar-Chia-Plot-Manager> python manager.py start
Traceback (most recent call last):
  File "manager.py", line 30, in <module>
    start_manager()
  File "D:\chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "D:\chia\Swar-Chia-Plot-Manager\plotmanager\library\parse\configuration.py", line 145, in get_config_info
    max_concurrent, max_for_phase_1, minimum_minutes_between_jobs = _get_global_config(config=config)
  File "D:\chia\Swar-Chia-Plot-Manager\plotmanager\library\parse\configuration.py", line 62, in _get_global_config
    _check_parameters(parameter=global_config, expected_parameters=expected_parameters, parameter_type='global')
  File "D:\chia\Swar-Chia-Plot-Manager\plotmanager\library\parse\configuration.py", line 133, in _check_parameters
    raise InvalidYAMLConfigException(f'Failed to find the following {parameter_type} parameters: '
plotmanager.library.utilities.exceptions.InvalidYAMLConfigException: Failed to find the following global parameters: max_for_phase_1, minimum_minutes_between_jobs
```

**Comment by adamsky-01** [comment]
SOLVED, new version has new config.yaml parameters and these were missing in my old config.yaml file.
