### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'date'

### ISSUE THREAD

**Issue by VictorVolpe** [swar/Swar-Chia-Plot-Manager#731]
Recurrent issue on Debian 10...

```
# python3.7 manager.py start
Plot Manager has started...
# python3.7 manager.py view
Traceback (most recent call last):
  File "manager.py", line 37, in <module>
    view()
  File "/usr/lib/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 160, in view
    analysis = analyze_log_dates(log_directory=log_directory, analysis=analysis)
  File "/usr/lib/Swar-Chia-Plot-Manager/plotmanager/library/utilities/log.py", line 77, in analyze_log_dates
    analysis = _get_date_summary(analysis)
  File "/usr/lib/Swar-Chia-Plot-Manager/plotmanager/library/utilities/log.py", line 36, in _get_date_summary
    end_date = analysis['files'][file_path]['data']['date'].date()
AttributeError: 'NoneType' object has no attribute 'date'
# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
# date
Sat 22 May 2021 03:01:04 AM -03
```

**Comment by limebinary** [comment]
I have the same problem, need to fix.

**Comment by winkee01** [comment]
I had the same issue, this is because dateparser() does not correctly parse the date

**Comment by VictorVolpe** [comment]
> 
> 
> I had the same issue, this is because dateparser() does not correctly parse the date

Nice, but how did you fix it?

**Comment by MartinGao** [comment]
I fixed this problem by using another lib `moment` instead of `dateparser`

here is what I did in case you are interested 
https://github.com/MartinGao/Swar-Chia-Plot-Manager/commit/b99039b4700fb88936ff623cb8438f74fedfaca2

but I have to say that I am not familiar with python at all.
I picked `moment` simply because I happened to find this lib and it happened to fix this problem. 
Using another lib might not be the best way to fix this problem and I think with correct usage `dateparser` should be able to do the job but I did not dig into it since python is not my first-choice programming language.

**Comment by laozhang713** [comment]
> I fixed this problem by using another lib `moment` instead of `dateparser`
> 
> here is what I did in case you are interested
> [MartinGao@b99039b](https://github.com/MartinGao/Swar-Chia-Plot-Manager/commit/b99039b4700fb88936ff623cb8438f74fedfaca2)
> 
> but I have to say that I am not familiar with python at all.
> I picked `moment` simply because I happened to find this lib and it happened to fix this problem.
> Using another lib might not be the best way to fix this problem and I think with correct usage `dateparser` should be able to do the job but I did not dig into it since python is not my first-choice programming language.

I fixed ! tks
