### ISSUE TITLE
Error starting - PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by Ocidentally** [swar/Swar-Chia-Plot-Manager#74]
Tried starting cmd and Powershell as administrator, but keep getting this error.

Traceback (most recent call last):
  File "C:\Users\peter\Swar-Chia-Plot-Manager\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\peter\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.

In the log file:

Traceback (most recent call last):
  File "C:\Users\peter\Swar-Chia-Plot-Manager\stateless-manager.py", line 58, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\peter\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 119, in monitor_jobs_to_start
    job, work = start_work(job=job, chia_location=chia_location, log_directory=log_directory)
  File "C:\Users\peter\Swar-Chia-Plot-Manager\plotmanager\library\utilities\jobs.py", line 169, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Users\peter\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 273, in start_process
    process = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by garthheff** [comment]
checked your antivirus to make sure it's not blocking it?

**Comment by Ocidentally** [comment]
I stopped my antivirus but got exactly the same result.

**Comment by garthheff** [comment]
> I stopped my antivirus but got exactly the same result.

anything in the windows event log?

**Comment by Ocidentally** [comment]
Thanks for responding but it's all a little above my head. Might try again later.

**Comment by allischalmersman** [comment]
I'm having this same error.  All antivirus turned off, and Powershell being run as admin
