### ISSUE TITLE
swar not start

### ISSUE THREAD

**Issue by newland33** [swar/Swar-Chia-Plot-Manager#768]
(ven) C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 138, in get_config_info
    config = _get_config()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\ven\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\config.yaml", line 190, column 5
could not find expected ':'
  in "C:\Users\4mypl\Downloads\Swar-Chia-Plot-Manager-main\Swar-Chia-Plot-Manager-main\config.yaml", line 191, column 5

**Comment by TaylorM87** [comment]
open your config.yaml file and look at line 190 it is complaining about a :

**Comment by newland33** [comment]
it was only the space betwen ...max_concurrent_with_start_early: 12...     the : and 12 .. now it works
