### ISSUE TITLE
 File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\scanner.py", line 577, in fetch_value     raise ScannerError(None, None,

### ISSUE THREAD

**Issue by robo145** [swar/Swar-Chia-Plot-Manager#789]
Hi, 

hit the start command but ended up twith error:

C:\Users\kapri\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\kapri\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\kapri\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "C:\Users\kapri\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 102, in get_config_info
    config = _get_config()
  File "C:\Users\kapri\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  **File "C:\Users\kapri\AppData\Roaming\Python\Python39\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,**
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\kapri\Swar-Chia-Plot-Manager-main\config.yaml", line 10, column 8

**Comment by iw777** [comment]
same error, doesn't seam to work also very fishy I need to write my keys to the yaml file... how safe is this?

I have 5TB of plots already, I shouldn't have done this shit.

**Comment by dmt155** [comment]
You don't need to put your keys in the tank file. By default it uses the keys that you have installed on your machine or through "chia keys add".
