### ISSUE TITLE
Cannot start  manager.py

### ISSUE THREAD

**Issue by royzhang12345678** [swar/Swar-Chia-Plot-Manager#790]
(venv) PS C:\Swar-Chia-Plot-Manager-main> python manager.py start
Traceback (most recent call last):
  File "C:\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "C:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 138, in get_config_info
    config = _get_config()
  File "C:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Swar-Chia-Plot-Manager-main\venv\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Swar-Chia-Plot-Manager-main\config.yaml", line 10, column 8

**Comment by 3xplain** [comment]
It is a spacing error some where in your line mine was in global there should be a space between : and the number

Also try pasting your config.yaml file here http://www.yamllint.com/
