### ISSUE TITLE
ubuntu20.04 RuntimeError

### ISSUE THREAD

**Issue by liaozhiping** [swar/Swar-Chia-Plot-Manager#817]
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1256, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 34, in plots_cmd
RuntimeError: Please initialize (or migrate) your config directory with 'chia init'
[5454] Failed to execute script chia

**Comment by creamsoup** [comment]
this is working as expected. you need to setup chia.
```bash
#change directory to chia
. ./activate
chia init
```
