### ISSUE TITLE
[Help!!!]Error run start on Ubuntu Ubuntu 20.04

### ISSUE THREAD

**Issue by giang21199z** [swar/Swar-Chia-Plot-Manager#847]
Hi. I ran on latest Ubuntu 20.04.
But I got an error message. Please help me.

**[config.yaml]**
![image](https://user-images.githubusercontent.com/11538834/119375190-b9c20e00-bce4-11eb-9690-5c7c9aaf8ed5.png)

**Command error when run start**
![image](https://user-images.githubusercontent.com/11538834/119375506-13c2d380-bce5-11eb-8d23-edc62d27e2e0.png)

**This is debug.log file**
![image](https://user-images.githubusercontent.com/11538834/119375640-3b19a080-bce5-11eb-98dc-900be34117f2.png)

**Comment by intruder04** [comment]
i'm experiencing the same issue. As a workaround, you can try `python3 stateless-manager.py`. You will have to keep that terminal open. `python3 manager.py view` can be started in another terminal

**Comment by BaraoVlask** [comment]
Same here

CMD output after python3 manager.py start
=
Traceback (most recent call last):
File "/home/ubuntu/chia/swar/manager.py", line 30, in
start_manager()
File "/home/ubuntu/chia/swar/plotmanager/library/utilities/commands.py", line 55, in start_manager
raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.

debug.log
=
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ubuntu/chia/swar/stateless-manager.py", line 94, in
jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
File "/home/ubuntu/chia/swar/plotmanager/library/utilities/jobs.py", line 258, in monitor_jobs_to_start
job, work = start_work(
File "/home/ubuntu/chia/swar/plotmanager/library/utilities/jobs.py", line 327, in start_work
psutil.Process(pid).nice(nice_val)
File "/home/ubuntu/.local/lib/python3.9/site-packages/psutil/init.py", line 724, in nice
self._proc.nice_set(value)
File "/home/ubuntu/.local/lib/python3.9/site-packages/psutil/_pslinux.py", line 1578, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=405039)

**Comment by j4r3kb** [comment]
Same, Ubuntu server 20.4 error when starting `python3 manager.py start`

**Comment by TegrityFarm** [comment]
I could not find much via google. But maybe there's a problem with Userrights. 
Try to open a new Terminal and give your folder / HDD full rights:

`sudo chmod 777 -c -R /location/folder`

For example: `sudo chmod 777 -c -R /home`

**Comment by intruder04** [comment]
It was fixed for me after I restarted my PC. An easy fix but hard to do that when you plot all the time

**Comment by BaraoVlask** [comment]
> I could not find much via google. But maybe there's a problem with Userrights.
> Try to open a new Terminal and give your folder / HDD full rights:
> 
> `sudo chmod 777 -c -R /location/folder`
> 
> For example: `sudo chmod 777 -c -R /home`

This is not recommended
