### ISSUE TITLE
error when analyze_logs

### ISSUE THREAD

**Issue by cjjltx** [swar/Swar-Chia-Plot-Manager#850]
(venv) ubuntu@XXXXXXX:~/Swar-Chia-Plot-Manager-main$ sudo python3 manager.py view
Traceback (most recent call last):
  File "manager.py", line 37, in <module>
    view()
  File "/home/ubuntu/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/commands.py", line 160, in view
    analysis = analyze_log_dates(log_directory=log_directory, analysis=analysis)
  File "/home/ubuntu/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/log.py", line 77, in analyze_log_dates
    analysis = _get_date_summary(analysis)
  File "/home/ubuntu/Swar-Chia-Plot-Manager-main/plotmanager/library/utilities/log.py", line 36, in _get_date_summary
    end_date = analysis['files'][file_path]['data']['date'].date()
AttributeError: 'NoneType' object has no attribute 'date'

**Comment by cjjltx** [comment]
Prefer to #731
