### ISSUE TITLE
Newb Install Issue

### ISSUE THREAD

**Issue by AOB8831** [swar/Swar-Chia-Plot-Manager#854]
I have latest python set to path. Requirements.txt seemed to install correction. I was given a warning to update pip version, which I did. Now selecting start seems to fail with the following:

c:\SwarPlotMgr>manager.py start
Traceback (most recent call last):
  File "C:\SwarPlotMgr\manager.py", line 30, in <module>
    start_manager()
  File "C:\SwarPlotMgr\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "C:\SwarPlotMgr\plotmanager\library\parse\configuration.py", line 138, in get_config_info
    config = _get_config()
  File "C:\SwarPlotMgr\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\saver\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\SwarPlotMgr\config.yaml", line 178, column 14

Probably something newb on my end, but I'd appreciate some help. Thanks.

**Comment by pckatil** [comment]
I have that same problem.

**Comment by wesray** [comment]
Last 2 line fellas, you need to have perfect formatting in yaml files (spaces mainly) , looks like a small typo:

yaml.scanner.ScannerError: mapping values are not allowed here
in "**C:\SwarPlotMgr\config.yam**l", **line 178**, column 14

**Comment by AOB8831** [comment]
Appreciate the tip wesray. I will super-check and update.

**Comment by AOB8831** [comment]
Get the bloody config.yaml right. Yes. A copy/paste from a saved yaml was the issue. Thank you.
