### ISSUE TITLE
windows： "D:\Swar\config.yaml", line 16, column 3

### ISSUE THREAD

**Issue by jlfsccm** [swar/Swar-Chia-Plot-Manager#868]
(venv) D:\Swar>python manager.py start
Traceback (most recent call last):
  File "D:\Swar\manager.py", line 30, in <module>
    start_manager()
  File "D:\Swar\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "D:\Swar\plotmanager\library\parse\configuration.py", line 138, in get_config_info
    config = _get_config()
  File "D:\Swar\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "D:\Swar\venv\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "D:\Swar\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\Swar\venv\lib\site-packages\yaml\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "D:\Swar\venv\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "D:\Swar\venv\lib\site-packages\yaml\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "D:\Swar\config.yaml", line 16, column 3

![360截图20210525200550847](https://user-images.githubusercontent.com/84188393/119495312-dfa6eb80-bd94-11eb-81ee-6b20f774a418.jpg)

**Comment by jlfsccm** [comment]
![222](https://user-images.githubusercontent.com/84188393/119495719-45937300-bd95-11eb-8b9c-50823630e73a.png)

**Comment by bitnaughty** [comment]
Try put an space before drive letter

**Comment by bardsnight** [comment]
You're not supposed to put manager path after "manager:".

**Comment by authrequest** [comment]
Have it look like this. As mentioned above - Remove the space and remove the path after manager

![chia](https://user-images.githubusercontent.com/42212841/119761283-61178000-be60-11eb-9336-26a03babd47a.png)

**Comment by jlfsccm** [comment]
谢谢大家的帮助
