### ISSUE TITLE
Cant start manager on MacOS 11.3

### ISSUE THREAD

**Issue by GameOSX** [swar/Swar-Chia-Plot-Manager#88]
Yesterday i was plotting with plot manager without any issues. Today it finished working, and when I want to start it again i'm getting this error all the time:

`psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=3311)`

Nothing is helping, first i've kill this process - still the same. Then rebooted the OS, started plot manager again - and again this error but with different pid.

This is from manager.log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/psutil/_psosx.py", line 365, in catch_zombie
    yield
  File "/usr/local/lib/python3.9/site-packages/psutil/_psosx.py", line 431, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abc/chia/hpool/Chia-Plot-Manager/stateless-manager.py", line 35, in <module>
    jobs, running_work = get_running_plots(jobs, running_work)
  File "/Users/abc/chia/hpool/Chia-Plot-Manager/plotmanager/library/utilities/processes.py", line 178, in get_running_plots
    if chia_executable_name not in process.name() and 'python' not in process.name().lower():
  File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 624, in name
    cmdline = self.cmdline()
  File "/usr/local/lib/python3.9/site-packages/psutil/__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "/usr/local/lib/python3.9/site-packages/psutil/_psosx.py", line 344, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/psutil/_psosx.py", line 431, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/psutil/_psosx.py", line 376, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=3311)
```

Even when i've created virtual environment for python - it's still the same.

**Comment by GameOSX** [comment]
Ok i've found what was it - it was zombie process from Adobe  Reader Updater :/ I'm closing this issue - but you should fix that if there are zombie processes not related to chia plotting - then your manager should start

**Comment by 24601** [comment]
I am also experiencing this, and while I agree this is not a zombie or a problem related to SCPM's processes, but zombie processes *do* occur and how the processing listing is being parsed could be improved to catch this error or ignore zombies that may exist in the process table, so in that way, this is a bug in SCPM in the sense it does not handle the gamut of possible inputs from the process table appropriately. 

I am willing to submit a PR to do this if it will be of use/merged, thoughts?

**Comment by aquabubble** [comment]
Just to note: I have the same issue. In my case it was more difficult to kill off the zombie processes and a restart was required on my Mac. I'd appreciate you looking at it @24601 - this is happening to me fairly frequently
