### ISSUE TITLE
Can't start on ubuntu linux error

### ISSUE THREAD

**Issue by colorprint** [swar/Swar-Chia-Plot-Manager#883]
Got error in log:

Traceback (most recent call last):                                                                                        File "/home/ubuntu/chia/chia-blockchain/venv/bin/chia", line 33, in <module>                                              sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())                                            File "/home/ubuntu/chia/chia-blockchain/chia/cmds/chia.py", line 77, in main                                              cli()  # pylint: disable=no-value-for-parameter                                                                       File "/home/ubuntu/chia/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__            return self.main(*args, **kwargs)                                                                                     File "/home/ubuntu/chia/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main                rv = self.invoke(ctx)                                                                                                 File "/home/ubuntu/chia/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke             return _process_result(sub_ctx.command.invoke(sub_ctx))                                                               File "/home/ubuntu/chia/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke             return _process_result(sub_ctx.command.invoke(sub_ctx))                                                               File "/home/ubuntu/chia/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke             return ctx.invoke(self.callback, **ctx.params)                                                                        File "/home/ubuntu/chia/chia-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke              return callback(*args, **kwargs)                                                                                      File "/home/ubuntu/chia/chia-blockchain/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func       return f(get_current_context(), *args, **kwargs)                                                                      File "/home/ubuntu/chia/chia-blockchain/chia/cmds/plots.py", line 135, in create_cmd                                      create_plots(Params(), ctx.obj["root_path"])                                                                          File "/home/ubuntu/chia/chia-blockchain/chia/plotting/create_plots.py", line 55, in create_plots                          farmer_public_key = G1Element.from_bytes(bytes.fromhex(args.farmer_public_key))                                     ValueError: Length of bytes object not equal to G1Element::SIZE  

How to fix it? Thanks!

**Comment by colorprint** [comment]
fixed, "0x" before fpk and ppk should be removed
