### ISSUE TITLE
MY Manager Status: Stopped but it is working background

### ISSUE THREAD

**Issue by kagemusyakin** [swar/Swar-Chia-Plot-Manager#905]
when i write python manager.py startd  ask 

![1111](https://user-images.githubusercontent.com/84070478/119650631-016ca500-be5f-11eb-9514-9342a105c8a8.png)
](url)

(venv) C:\Users\xxxx\Desktop\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\xxxx\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.

when i write  restart ask me
(venv) C:\Users\xxx\Desktop\Swar-Chia-Plot-Manager-main>python manger.py restart
C:\Program Files\Python39\python.exe: can't open file 'C:\Users\xxxx\Desktop\Swar-Chia-Plot-Manager-main\manger.py': [Errno 2] No such file or directory

### ****

**Comment by kagemusyakin** [comment]
![微信图片_20210526195021](https://user-images.githubusercontent.com/84070478/119651047-835cce00-be5f-11eb-9039-91251e79a9e2.png)
![微信图片_20210526195119](https://user-images.githubusercontent.com/84070478/119651050-83f56480-be5f-11eb-8d8c-cf14c68ca3e6.png)

**Comment by jnjus** [comment]
Same thing here. I've defined the appropriate amount of threads/RAM to my system (1 TB NVMe, 8-core/16-thread Ryzen, 32GB of RAM) for my config.yaml file (Max concurrent in P1: 2, 100 min stagger, max current 4, 5 If start early). 

Manager will just suddenly stop, the new plots never spin up.

**Comment by ristraman** [comment]
I had a similar experience tonight. I was getting some less than optimum plot times, stopped the manager on two machines, changed some parameters (increased threads, reduced max parallel plots) and started the manager again. I launched the viewer and when the still running plots appeared. When it was time for a new plot to launch, the status of the manager changed to stopped. I exited the viewer and restarted the manager, back to the viewer same thing happens (both machines).

**Comment by kagemusyakin** [comment]
Resolved！I had set config some parameters. and settle one ssd parameters，and elete another

**Comment by jnjus** [comment]
> Resolved！I had set config some parameters. and settle one ssd parameters，and elete another

Can you please be more specific?
