### ISSUE TITLE
Not working when trying to start it

### ISSUE THREAD

**Issue by SaharPR** [swar/Swar-Chia-Plot-Manager#913]
it write me this:
:\Users\hotca\Desktop\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\hotca\Desktop\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\hotca\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.
and then when I go to debug it write this:
  File "C:\Users\hotca\Desktop\Swar-Chia-Plot-Manager-main\stateless-manager.py", line 14, in <module>
    instrumentation_settings = get_config_info()
  File "C:\Users\hotca\Desktop\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 143, in get_config_info
    os.makedirs(log_directory)
  File "C:\Program Files\Python39\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Program Files\Python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not bool
what can I do?

**Comment by creamsoup** [comment]
what's your chia config looks like (log section)? also probably a good idea to paste related part of debug.log.

**Comment by Jeff-newguy** [comment]
what version of chia application?  I think I had a similar issue and got it working with 1.1.5

**Comment by SaharPR** [comment]
How do I run it on 1.1.5 if i updated to 1.1.6?

**Comment by SaharPR** [comment]
> what's your chia config looks like (log section)? also probably a good idea to paste related part of debug.log.

What do you mean by chia config?

**Comment by SaharPR** [comment]
> what's your chia config looks like (log section)? also probably a good idea to paste related part of debug.log.

ok I fixed it I created a folder for the logs thanks
