### ISSUE TITLE
Issue on startup

### ISSUE THREAD

**Issue by Jeff-newguy** [swar/Swar-Chia-Plot-Manager#928]
Hello,

Sorry if this is a user error.  I already have this running on another machine but cannot figure this error out to get it to run.  This Swar version looks newer....

PS C:\users\004\desktop\swar> python manager.py start
Traceback (most recent call last):
  File "C:\users\004\desktop\swar\manager.py", line 30, in <module>
    start_manager()
  File "C:\users\004\desktop\swar\plotmanager\library\utilities\commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.
PS C:\users\004\desktop\swar>

in the debug.log
2021-05-26 21:26:10 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\Users\004\Desktop\Swar\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\Program Files\Python39\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Program Files\Python39\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\Users\004\Desktop\Swar\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\004\Desktop\Swar\plotmanager\library\utilities\jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Users\004\Desktop\Swar\plotmanager\library\utilities\jobs.py", line 284, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\Users\004\Desktop\Swar\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\Users\004\Desktop\Swar\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\Users\004\Desktop\Swar\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by Jeff-newguy** [comment]
Ahhhh..... was simply an error destination drive text in the config file.....

**Comment by Jeff-newguy** [comment]
I thought for a moment that I had it fixed, but that was false.  Still looking for a solution.

**Comment by Jeff-newguy** [comment]
ok, just found the issue.  The swar does not work with the latest Chia application 1.1.6.  

Swar plot manager worked first time after I uninstalled Chia 1.1.6 and installed 1.1.5
