### ISSUE TITLE
Debug.log - Permission denied (errno 13)

### ISSUE THREAD

**Issue by Matt-Mayor** [swar/Swar-Chia-Plot-Manager#933]
Hello All!

I have an issue after pip install... 

My view in CMD:

C:\Program Files\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Program Files\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Program Files\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 30, in start_manager
    debug_log_file = open(debug_log_file_path, 'a')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Swar-Chia-Plot-Manager-main\\debug.log'

For any help will be highly grateful. 
Thanks in advance.

**Comment by lsHaKeRl** [comment]
Hi, you ran the CMD with Admin? Can you send the "DEBUG.LOG"?!
You can find it in the MAINFolder of Plotmanager. 

Greetings :)

**Comment by Matt-Mayor** [comment]
Fixed. Thank you buddy. 

I was doing this by team-viewer.
