### ISSUE TITLE
[WinError 6] on Windows 7

### ISSUE THREAD

**Issue by Novgorod** [swar/Swar-Chia-Plot-Manager#936]
I'm using Python 3.8.10, which is the latest version that supports Windows 7 x64. The manager fails to start and outputs this in the debug.log:
`Traceback (most recent call last):
  File "C:\Users\REDACTED\Downloads\Plot-Manager\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "C:\Users\REDACTED\Downloads\Plot-Manager\plotmanager\library\utilities\jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "C:\Users\REDACTED\Downloads\Plot-Manager\plotmanager\library\utilities\jobs.py", line 322, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "C:\Users\REDACTED\Downloads\Plot-Manager\plotmanager\library\utilities\processes.py", line 277, in start_process
    process = subprocess.Popen(
  File "C:\Program Files\Python38\lib\subprocess.py", line 808, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Program Files\Python38\lib\subprocess.py", line 1161, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\Program Files\Python38\lib\subprocess.py", line 1208, in _make_inheritable
    h = _winapi.DuplicateHandle(
OSError: [WinError 6] The handle is invalid
`
It creates an empty log file in the log folder with the first job name and then aborts without starting the chia process. I assume it's not a config issue because the same config (except for minor folder changes) works fine on other PCs with Windows 10, so it must be related to Windows 7. I know the OS is too old to request proper support, I'm just hoping a quick fix is possible by modifying how the subprocess is started...

**Comment by Novgorod** [comment]
Ok, after some digging I found a solution! Turns out that you have to pass a _stdin_ handle to the _subprocess.popen_ function for a detached process (no console) in Windows versions before Windows 8. You can simply use an empty file handle like `stdin=subprocess.DEVNULL`. Just add this line in processes.py:

>    process = subprocess.Popen(
>       args=args,
>      stdout=log_file,
>        stderr=log_file,
>        **stdin=subprocess.DEVNULL,**
>        shell=False,
>        **kwargs,
    )

**Comment by gituserwork** [comment]
> Ok, after some digging I found a solution! Turns out that you have to pass a _stdin_ handle to the _subprocess.popen_ function for a detached process (no console) in Windows versions before Windows 8. You can simply use an empty file handle like `stdin=subprocess.DEVNULL`. Just add this line in processes.py:
> 
> > process = subprocess.Popen(
> > args=args,
> > stdout=log_file,
> > stderr=log_file,
> > **stdin=subprocess.DEVNULL,** #<--
> > shell=False,
> > **kwargs,
> > )

hi 
I have the same error 

`Traceback (most recent call last):
  File "D:\!_Swar\stateless-manager.py", line 94, in <module>
    jobs, running_work, next_job_work, next_log_check = monitor_jobs_to_start(
  File "D:\!_Swar\plotmanager\library\utilities\jobs.py", line 258, in monitor_jobs_to_start
    job, work = start_work(
  File "D:\!_Swar\plotmanager\library\utilities\jobs.py", line 322, in start_work
    process = start_process(args=plot_command, log_file=log_file)
  File "D:\!_Swar\plotmanager\library\utilities\processes.py", line 277, in start_process
    process = subprocess.Popen(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 808, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1161, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1208, in _make_inheritable
    h = _winapi.DuplicateHandle(
OSError: [WinError 6] Неверный дескриптор`


in
D:\!_Swar\plotmanager\library\utilities\

im add you code


[processes.zip](https://github.com/swar/Swar-Chia-Plot-Manager/files/6627520/processes.zip)

and have new  error

D:\!_Swar>python manager.py start
Traceback (most recent call last):
  File "manager.py", line 4, in <module>
    from plotmanager.library.utilities.commands import start_manager, stop_manager, view, json_output, analyze_logs
  File "D:\!_Swar\plotmanager\library\utilities\commands.py", line 13, in <module>
    from plotmanager.library.utilities.jobs import load_jobs
  File "D:\!_Swar\plotmanager\library\utilities\jobs.py", line 9, in <module>
    from plotmanager.library.utilities.processes import identify_drive, is_windows, start_process
  File "D:\!_Swar\plotmanager\library\utilities\processes.py", line 17, in <module>
    args = args,
NameError: name 'args' is not defined

**Comment by Novgorod** [comment]
Hi!

Did you delete your comment from github?

Anyway, your processes.py is wrong, you modified it incorrectly. Don't 
add the whole code block, ONLY add the SINGLE bold line 
(stdin=subprocess.DEVNULL,) into the existing code block in your 
original processes.py. The code block is at the bottom of the file and 
the exact place to insert the bold line should be 4 lines from the end.

Good luck...
