### ISSUE TITLE
[ERROR]: Failed to get disk_usage of drive None.   for Ubuntu

### ISSUE THREAD

**Issue by koushui** [swar/Swar-Chia-Plot-Manager#953]
Got error in log:

2021-05-28 02:39:23 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "/home/chia/Swar-Chia-Plot-Manager/plotmanager/library/utilities/jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "/home/chia/.local/lib/python3.8/site-packages/psutil/__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "/home/chia/.local/lib/python3.8/site-packages/psutil/_psposix.py", line 169, in disk_usage
    st = os.statvfs(path)

**Comment by Plotman-Ed** [comment]
Do you have an extra line after your final job group?

**Comment by wacher74** [comment]
Use uppercase drive letters in _directory parameters.
v:\chia is wrong
V:\chia is good.
This helped me.
