### ISSUE TITLE
[WinError 433] A device which does not exist was specified: 'I:\\plot-k32-2021-05-28-06-45-8c78997b6c2499bd8bd59455afd3098bc4e958aafd4e2267d62a721a4b1bb082.plot.table1.tmp'

### ISSUE THREAD

**Issue by cyperbg** [swar/Swar-Chia-Plot-Manager#969]
So I tried adding a 2nd destination drive by changing to max_plots: 1 for the current jobs and then creating new jobs.
This didn't work as it told me I can't have the same temporary directory for different jobs.
Anyway now I can't start the manager as I get this error:

`Traceback (most recent call last):
  File "C:\Swar\stateless-manager.py", line 43, in <module>
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work,
  File "C:\Swar\plotmanager\library\utilities\processes.py", line 238, in get_running_plots
    temp_file_size = get_temp_size(plot_id=plot_id, temporary_directory=temporary_directory,
  File "C:\Swar\plotmanager\library\utilities\processes.py", line 167, in get_temp_size
    temp_size += os.path.getsize(file_path)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [WinError 433] A device which does not exist was specified: 'I:\\plot-k32-2021-05-28-06-45-8c78997b6c2499bd8bd59455afd3098bc4e958aafd4e2267d62a721a4b1bb082.plot.table1.tmp'`

What happened?
Judging by the task manager plotting has died.

**Comment by choudharydhaka** [comment]
Hey mate, I got the same, out of the blue, did you find any solution?

**Comment by cyperbg** [comment]
> Hey mate, I got the same, out of the blue, did you find any solution?

I believe it's a problem with the ssd. Nothing to do with Swar or Chia.

**Comment by choudharydhaka** [comment]
I think you are right, I had to delete all the processes stuck with the SSD and then restart it back again.
